// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Evented dojo/on dojo/Deferred dijit/_WidgetBase ./utils jimu/utils jimu/LayerInfos/LayerInfos jimu/DataSourceManager esri/geometry/geometryEngine esri/tasks/query esri/tasks/QueryTask esri/tasks/StatisticDefinition esri/layers/FeatureLayer".split(" "),function(p,d,q,f,m,r,t,h,u,v,w,x,y,k,z){return p([r,q],{oidFieldType:"esriFieldTypeOID",constructor:function(a){this.map=a.map;this.appConfig=a.appConfig;this.useSelection=a.useSelection;this.filterByExtent=
a.filterByExtent;this.dijit=a.dijit;this.dataSource=a.dataSource;this.layerInfosObj=u.getInstanceSync();this.dataSourceManager=v.getInstance();this._layerUrl=this.layerObject=null;this.dijit&&(this.config=this.dijit.config)&&(this.isDateType=!!this.config.dateConfig);"DATA_SOURCE_FROM_FRAMEWORK"===this.dataSource.dataSourceType&&(this.frameWorkDsId=this.dataSource.frameWorkDsId);this.exdsBeginUpdateHandle=this.timeIntervalHandle=this.filterChangedHandle=this.updateEndHandle=this.refreshIntervalHandle=
this.selectionHandle=this.exchetChangeHandle=this._oldQueryParameter=this._queryParameter=null},start:function(){this._tryGetLayerObject().then(function(){this._onFetchSuccess();this.awake();this._listenEventsContinuousAccessFeatures()}.bind(this),function(a){this._onFetchField(a)}.bind(this))},awake:function(){this.sleeping=!1;this._getFeaturesForFirst()},sleep:function(){this.sleeping=!0},destroy:function(){this._removeHandles();this.inherited(arguments)},setAppConfigDSFeatures:function(a){this.sleeping||
"DATA_SOURCE_FROM_FRAMEWORK"!==this.dataSource.dataSourceType||(this._onFetchSuccess(),this._onDataUpdate(a))},_getFeaturesForFirst:function(){if("DATA_SOURCE_FROM_FRAMEWORK"===this.dataSource.dataSourceType){var a=this.dataSourceManager.getData(this.dataSource.frameWorkDsId);a&&this._onDataUpdate(a.features)}else"DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===this.dataSource.dataSourceType&&this._trigerCallback()},_listenEventsContinuousAccessFeatures:function(){if("DATA_SOURCE_FROM_FRAMEWORK"===this.dataSource.dataSourceType)this._resetExdsBeginUpdateHandle(),
this.exdsBeginUpdateHandle=f(this.dataSourceManager,"begin-update",d.hitch(this,function(a){a===this.frameWorkDsId&&this._onFetch()}));else if(this.layerObject&&this.layerInfo){var a=this._shouldAccessClientFeatures();this.useSelection&&(this._resetSelectionHandle(),this.selectionHandle=f(this.layerObject,"selection-complete,selection-clear",d.hitch(this,function(){this._trigerCallback()})));a||(this._resetFilterChangedHandle(),this.filterChangedHandle=f(this.layerInfo,"filterChanged",d.hitch(this,
function(){this._trigerCallback()})));a&&(this._resetUpdateEndHandle(),this.updateEndHandle=f(this.layerObject,"update-end",d.hitch(this,function(){this._trigerCallback()})));this.filterByExtent&&this.map&&(this._resetExtentChangeHandle(),this.exchetChangeHandle=f(this.map,"extent-change",d.hitch(this,function(){this._trigerCallback(!0)})));a||(this._setTimeListener(),this._resetRefreshIntervalHandle(),this.refreshIntervalHandle=f(this.layerObject,"refresh-interval-change",d.hitch(this,this._setTimeListener)))}},
_setTimeListener:function(){var a=this._getLayerRefreshInterval();a?(this._resetTimeIntervalHandle(),this.timeIntervalHandle=setInterval(d.hitch(this,function(){this._trigerCallback()}),6E4*a)):this._resetTimeIntervalHandle()},_trigerCallback:function(a){var b=this.computingTheWayToGetFeatures();if(!a||2!==b||!this._isLayerOnDemandMode())switch(b){case 1:this._getFeaturesFromSelection(this.map,this.layerObject,this.filterByExtent,d.hitch(this,this._onDataUpdate));break;case 2:this._getClientFeaturesFromMap(this.map,
this.layerObject,this.filterByExtent,d.hitch(this,this._onDataUpdate));break;case 3:this._getStatisticsFeaturesForServer(d.hitch(this,this._onDataUpdate))}},computingTheWayToGetFeatures:function(){var a=0;return this.sleeping||!this.layerObject?a:a=this._isMapLayer()?this._shouldAccessFeaturesBySelection()?1:this._shouldAccessClientFeatures()?2:3:0},_getClientFeaturesFromMap:function(a,b,c,g){var e=b.graphics;c&&(e=this._filterFeaturesByExtent(a.extent,e));e=this._sortClientFeaturesByObjID(e,b);g(e)},
_getFeaturesFromSelection:function(a,b,c,g){var e=[],l=!1,e=b.getSelectedFeatures(),l=!0;c&&(e=this._filterFeaturesByExtent(a.extent,e));e.isSelectedFeatures=l;e=this._sortClientFeaturesByObjID(e,b);g(e)},_getStatisticsFeaturesForServer:function(a){this._updateLayerInfoFilter();this._tryGenerateQueryParameter();this._shouldLaunchQuery()&&(this._onFetch(),this.queryDeferred=this._doQuery(),this.queryDeferred.then(d.hitch(this,function(b){this.queryDeferred=null;this._onFetchSuccess();b=b.features||
[];b=this._calculateAverageWithNullValueAsZero(b);a(b,!0)}),d.hitch(this,function(a){this.queryDeferred=null;this._onFetchField(a)})))},_updateLayerInfoFilter:function(){if(this.dataSource&&"undefined"!==typeof this.dataSource.layerId){var a=this.layerInfosObj.getLayerInfoById(this.dataSource.layerId);a&&(this._layerFilter=a.getFilter())}},_onFetch:function(){this.emit("fetching")},_onFetchSuccess:function(){this.emit("success")},_onFetchField:function(a){this.emit("faild",a)},_onDataUpdate:function(a,
b){var c=null;"number"===this.dijit.type||"gauge"===this.dijit.type?c=this._getValueForNumberOrGauge(a):"chart"===this.dijit.type&&(c={features:a,hasStatisticsed:!!b});this.emit("data-update",c)},_getValueForNumberOrGauge:function(a){if("number"!==this.dijit.type&&"gauge"!==this.dijit.type)return a;var b=a;if(this._isNeededCalculateForClient())b=t.getSingleValueFromFeatures(this.config.statistic,this.dataSource,a);else{if(a&&a.length){if(a=a[0].attributes){var c=Object.keys(a)[0];c&&(b=a[c])}}else Array.isArray(a)&&
(b=0);b=Number(b)}return b},_isMapLayer:function(){return"DATA_SOURCE_FEATURE_LAYER_FROM_MAP"===this.dataSource.dataSourceType},_isLayerOnDemandMode:function(){return this.layerObject&&this.layerObject.currentMode===z.MODE_ONDEMAND},_shouldAccessFeaturesBySelection:function(){return this.useSelection&&this.layerObject&&this.layerObject.getSelectedFeatures().length},_shouldAccessClientFeatures:function(){var a=this.config&&"feature"===this.config.mode,b=this.isDateType,c=this._isSupportServerStatByExtent();
return a||b||!c},_isSupportServerStatByExtent:function(){var a=this.layerObject&&this.layerObject.version&&10.11<=Number(this.layerObject.version),b=this._isLayerSupportStatistics();return a&&b},_isLayerSupportStatistics:function(){if(this.layerObject){var a=!1;return a=this.layerObject.advancedQueryCapabilities?!!this.layerObject.advancedQueryCapabilities.supportsStatistics:!!this.layerObject.supportsStatistics}},_getLayerRefreshInterval:function(){if(this.layerObject&&this.layerObject.refreshInterval)return this.layerObject.refreshInterval},
_sortClientFeaturesByObjID:function(a,b){if(0<a.length){var c=h.getObjectIdField(b);c&&(b=a[0])&&b.attributes&&b.attributes.hasOwnProperty(c)&&a.sort(function(a,b){a.attributes||(a.attributes={});b.attributes||(b.attributes={});a=a.attributes[c];b=b.attributes[c];return a<b?-1:a>b?1:0})}return a},_filterFeaturesByExtent:function(a,b){var c=a.normalize();return b=b.filter(d.hitch(this,function(a){try{if(a.geometry){var b="point"===a.geometry.type||"multipoint"===a.geometry;return c.some(d.hitch(this,
function(c){return b?c.contains(a.geometry):w.intersects(c,a.geometry)}))}}catch(l){console.error(l)}return!1}))},_calculateAverageWithNullValueAsZero:function(a){if(!this._shouldCalcAvgForNullValue()||!a||!a.length)return a;var b=this.config.valueFields;if(!b||!b.length)return a;var c=b.map(function(a){return a+"_sum"});a.forEach(function(a){var b=a.attributes;if(b){var d=b.STAT_COUNT;"undefined"===typeof d?(d=b.stat_count,delete b.stat_count):delete b.STAT_COUNT;var g,f,n;c.forEach(function(a){n=
a.replace(/_SUM$/gi,"");var c=h.upperCaseString(a);a=h.lowerCaseString(a);var e=h.upperCaseString(n+"_AVG");g=b[c];"undefined"===typeof g?(g=b[a],delete b[a]):delete b[c];!g&&"number"!==typeof g||!d?b[e]=null:(f=g/d,b[e]=f)})}});return a},_shouldCalcAvgForNullValue:function(){var a=this.config&&this.config.mode;return a&&("category"===a||"field"===a)&&this.config.nullValue&&"average"===this.config.operation},_shouldLaunchQuery:function(){var a=!0,b=!(!this.queryDeferred||this.queryDeferred.isResolved()||
this.queryDeferred.isRejected()),c=h.isEqual(this._queryParameter,this._oldQueryParameter);b&&c&&(a=!1);this._oldQueryParameter=d.clone(this._queryParameter);return a},_getOutStatistics:function(a,b,c){var d=c;"average"===d&&(d="avg");var e=this.config.nullValue;e&&"avg"===d&&(d="sum");var f=null;"category"===a||"field"===a?b&&b.length&&(f=b.map(function(a){var b=h.upperCaseString(a+"_"+d),c=new k;c.statisticType=d;c.onStatisticField=a;c.outStatisticFieldName=b;return c}.bind(this)),a=null,e&&"average"===
c&&(a=new k,a.statisticType="count",a.onStatisticField="*",a.outStatisticFieldName="STAT_COUNT",f.push(a))):"count"===a&&(c=new k,c.statisticType="count",c.onStatisticField=this._getCountTypeOnStatisticsField(),c.outStatisticFieldName="STAT_COUNT",f=[c]);return f},_tryGenerateQueryParameter:function(){this._queryParameter={};this._layerUrl&&(this._queryParameter.url=this._layerUrl);this._layerFilter&&(this._queryParameter.where=this._layerFilter);if(this.dijit){var a;if("number"===this.dijit.type||
"gauge"===this.dijit.type){if(this.config&&this.config.statistic){var b=this.config.statistic;a=b.statisticsType;var c=b.fieldName,d=h.upperCaseString(c+"_"+a);"Features"===b.type&&(c=this._getCountTypeOnStatisticsField(),a="count",d="STAT_COUNT");"average"===a&&(a="avg");b=new k;b.statisticType=a;b.onStatisticField=c;b.outStatisticFieldName=d;this._queryParameter.outStatistics=[b]}}else"chart"===this.dijit.type&&this.config&&(this.statisticsByServer=!0,a=this.config.mode,this._queryParameter.outStatistics=
this._getOutStatistics(a,this.config.valueFields,this.config.operation),c=this.config.categoryField,"category"===a||"count"===a)&&(this._queryParameter.groupByFieldsForStatistics=[c])}},_getCountTypeOnStatisticsField:function(){var a=null;this.layerObject&&(a=(a=(a=this.layerObject.fields)&&a.filter(function(a){return a.type===this.oidFieldType}.bind(this))[0])&&a.name);return a||"*"},_doQuery:function(){var a=new m;if(!this._queryParameter)return a.reject("Empty query parameter."),a;if(!this._queryParameter.url)return a.reject("Empty layer url."),
a;var b=new y(this._queryParameter.url),c=new x;c.where=this._queryParameter.where||"1\x3d1";c.returnGeometry=!1;this.dataSource.filterByExtent&&this.map&&(c.geometry=this.map.extent);this._queryParameter.groupByFieldsForStatistics&&(c.groupByFieldsForStatistics=this._queryParameter.groupByFieldsForStatistics);if(this._hasVaildOutStatistics(this._queryParameter.outStatistics))c.outStatistics=this._queryParameter.outStatistics;else return a.reject("Invaild outStatistics of query params."),a;this._queryParameter.orderByFields&&
(c.orderByFields=this._queryParameter.orderByFields);return b.execute(c)},_hasVaildOutStatistics:function(a){return a&&a.length?a.every(function(a){return this._isTrueOrZero(a.onStatisticField)&&this._isTrueOrZero(a.outStatisticFieldName)&&!!a.statisticType}.bind(this)):!1},_isTrueOrZero:function(a){return!!a||0===a},_tryGetLayerObject:function(){var a=new m;if("DATA_SOURCE_FEATURE_LAYER_FROM_MAP"!==this.dataSource.dataSourceType)return a.resolve(),a;this._onFetch();var b=this.layerInfosObj.getLayerInfoById(this.dataSource.layerId);
if(b)return this.layerInfo=b,b.getLayerObject().then(d.hitch(this,function(a){this.layerObject=a;this._layerUrl=this.layerObject.url}));a.reject("invaild data source");return a},_isNeededCalculateForClient:function(){var a=this.layerObject&&this.useSelection&&0<this.layerObject.getSelectedFeatures().length,b="DATA_SOURCE_FROM_FRAMEWORK"===this.dataSource.dataSourceType,c=this._isSupportServerStatByExtent();return a||b||!c},_resetExtentChangeHandle:function(){this.exchetChangeHandle&&this.exchetChangeHandle.remove&&
(this.exchetChangeHandle.remove(),this.exchetChangeHandle=null)},_resetUpdateEndHandle:function(){this.updateEndHandle&&this.updateEndHandle.remove&&(this.updateEndHandle.remove(),this.updateEndHandle=null)},_resetFilterChangedHandle:function(){this.filterChangedHandle&&this.filterChangedHandle.remove&&(this.filterChangedHandle.remove(),this.filterChangedHandle=null)},_resetSelectionHandle:function(){this.selectionHandle&&this.selectionHandle.remove&&(this.selectionHandle.remove(),this.selectionHandle=
null)},_resetRefreshIntervalHandle:function(){this.refreshIntervalHandle&&this.refreshIntervalHandle.remove&&(this.refreshIntervalHandle.remove(),this.refreshIntervalHandle=null)},_resetTimeIntervalHandle:function(){this.timeIntervalHandle&&(clearInterval(this.timeIntervalHandle),this.timeIntervalHandle=null)},_resetExdsBeginUpdateHandle:function(){this.exdsBeginUpdateHandle&&this.exdsBeginUpdateHandle.remove&&(this.exdsBeginUpdateHandle.remove(),this.exdsBeginUpdateHandle=null)},_removeHandles:function(){this._resetExtentChangeHandle();
this._resetUpdateEndHandle();this._resetFilterChangedHandle();this._resetSelectionHandle();this._resetRefreshIntervalHandle();this._resetTimeIntervalHandle();this._resetSelectionHandle()}})});