// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/array dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/on dojo/string ./convert ./settingComponents ./SettingBoxedDivs ./SettingBufferBlock ./SettingCheckboxLabeled ./SettingContainer ./SettingDropdownLabeled ./SettingFieldListLabeled ./SettingInputLabeled ./SettingObject ./SettingOptionsTable".split(" "),function(f,v,e,p,q,w,k,r,l,x,t,g,m,u,y,d,z,A){return v(z,{_inputControl:null,_mainControl:null,_detailsDiv:null,_detailsTitle:null,_detailsCheckbox:null,
_sourceDisplay:null,_iCurrentSource:-1,_sourceMenuItems:[],_newSourceTypeMenuItems:[],_nls:null,_webmapFeatureLayers:[],_fieldListPicker:null,_displayFieldInput:null,constructor:function(a,b,c,h){this._nls=b;this._webmapFeatureLayers=h;this._newSourceTypeMenuItems=[b.groupingLabels.featureLayerDetails,b.groupingLabels.geocoderDetails];this._inputControl=new A(null,"third-width","",b.propertyLabels.name,null,"",e.hitch(this,this._onRowSelected),e.hitch(this,this._onRowDeleted),e.hitch(this,this._onRowMoved));
this._detailsDiv=l.container("two-thirds-width optionsTableHeaderHeight","majorTrailingVertGap",[]);a=l.addTextButtonDropdownCtl("",b.buttons.addSearchSource,this._newSourceTypeMenuItems);this.own(w(a.ctl,"click",e.hitch(this,this._onAddSearchSourceMenuItemClick)));this._mainControl=new m(null,c||"","majorTrailingVertGap",b.groupingLabels.searchSources,"full-width",[new d("allPlaceholder",!1,"full-width","third-width","two-thirds-width",b.propertyLabels.placeholderTextForAllSources),new g("showInfoWindowOnSelect",
"full-width","third-width","two-thirds-width",b.propertyLabels.showPopupForFoundItem),new x(null,[a.div,l.container("full-width flexbox","majorTrailingHorizGap",[this._inputControl.div(),this._detailsDiv])])]);this._mainDiv=this._mainControl.div()},setConfig:function(){this._mainControl.setConfig(this._config);this._config.sources=f.filter(this._config.sources,e.hitch(this,function(a){return"locator"===a.type||"query"===a.type&&f.some(this._webmapFeatureLayers,function(b){return a.layerId===b.layerId})}));
this._sourceMenuItems=f.map(this._config.sources,function(a){return{item:a.name}});this._inputControl.setValue(this._sourceMenuItems);0<this._sourceMenuItems.length&&this._inputControl.selectTableRow(0)},getConfig:function(a,b){this._mainControl.getConfig(this._config);this._setDetails(-1);f.forEach(this._config.sources,function(a){"locator"===a.type?a.url||b.push(k.substitute(this._nls.problems.noSearchSourceURL,{sourceName:a.name})):0===a.searchFields.length&&b.push(k.substitute(this._nls.problems.noSearchSourceFields,
{sourceName:a.name}));0>a.buffer.bufferUnitsMenu[0].indexOf("1")&&b.push(k.substitute(this._nls.problems.noBufferUnitsForSearchSource,{sourceName:a.name}))},this)},_onAddSearchSourceMenuItemClick:function(a){var b={};a.target.innerText===this._newSourceTypeMenuItems[0]?(a=e.clone(this._config.searchSourceTemplates.query),a.name=this._webmapFeatureLayers[0].name,a.displayField=this._webmapFeatureLayers[0].displayField,a.layerId=this._webmapFeatureLayers[0].layerId,a.url=this._webmapFeatureLayers[0].url):
(a=e.clone(this._config.searchSourceTemplates.locator),a.singleLineFieldName=null);a.buffer=e.clone(this._config.bufferTemplate);this._config.sources.push(a);b.item=a.name;this._sourceMenuItems.push(b);this._inputControl.addRowToTable(b);this._inputControl.selectTableRow(this._config.sources.length-1)},_setDetails:function(a){var b=this._sourceMenuItems.length,c,h=[],n=[];this._removeCurrentDetails();0<=a&&a<b&&(c=this._config.sources[a],"query"===c.type?(f.map(this._webmapFeatureLayers,function(a){h.push({label:a.name,
value:a.layerId});c.layerId===a.layerId&&f.map(a.fields,function(a){n.push({label:a.alias||a.name,value:a.name})})}),this._fieldListPicker=new y("searchFields",this._nls,"full-width","details-label","details-value",this._nls.propertyLabels.searchFields,this._nls.hints.csvNameList,n),this._displayFieldInput=new u("displayField","full-width","details-label","details-value",this._nls.propertyLabels.displayField,"",n,e.hitch(this,this._onChangeField)),this._sourceDisplay=new m(null,"","majorTrailingVertGap",
this._nls.groupingLabels.featureLayerDetails,"full-width",[new u("name","full-width","details-label","details-value",this._nls.propertyLabels.name,"",h,e.hitch(this,this._onChangeFeatureLayer)),new d("placeholder",!1,"full-width","details-label","details-value",this._nls.propertyLabels.placeholderText),this._fieldListPicker,this._displayFieldInput,new d("maxSuggestions",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumSuggestions,"6",null,null,null,{min:1,max:10,places:0}),
new d("maxResults",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumResults,"6",null,null,null,{min:1,max:10,places:0}),new d("zoomScale",!0,"full-width","details-label","details-value",this._nls.propertyLabels.zoomScale,"50000","","1:",null,{min:0,places:0}),new g("exactMatch","full-width","details-label","details-value",this._nls.propertyLabels.exactMatch),new g("searchInCurrentMapExtent","full-width","details-label","details-value",this._nls.propertyLabels.limitSearchToMapExtent),
new t("buffer",this._nls,"full-width","details-label","details-value",this._config.bufferTemplate,this._nls.propertyLabels.bufferDefaultDistance,"100")]),c.name=this._convertLayerNameToLayerId(c.name)):"locator"===c.type&&(this._sourceDisplay=new m(null,"","majorTrailingVertGap",this._nls.groupingLabels.geocoderDetails,"full-width",[new d("url",!1,"full-width","details-label","details-value",this._nls.propertyLabels.url),new d("name",!1,"full-width","details-label","details-value",this._nls.propertyLabels.name),
new d("placeholder",!1,"full-width","details-label","details-value",this._nls.propertyLabels.placeholderText),new d("countryCode",!1,"full-width","details-label","details-value",this._nls.propertyLabels.countryRegionCodes,this._nls.placeholders.countryRegionCodes),new d("maxSuggestions",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumSuggestions,"6",null,null,null,{min:1,max:10,places:0}),new d("maxResults",!0,"full-width","details-label","details-value",this._nls.propertyLabels.maximumResults,
"6",null,null,null,{min:1,max:10,places:0}),new d("zoomScale",!0,"full-width","details-label","details-value",this._nls.propertyLabels.zoomScale,"50000","","1:",null,{min:0,places:0}),new g("searchInCurrentMapExtent","full-width","details-label","details-value",this._nls.propertyLabels.limitSearchToMapExtent),new t("buffer",this._nls,"full-width","details-label","details-value",this._config.bufferTemplate,this._nls.propertyLabels.bufferDefaultDistance,"100")])),this._sourceDisplay&&(c.buffer.bufferUnitsMenu=
r.unitCodesToLabels(jimuNls.units,c.buffer.bufferUnitsMenu),this._sourceDisplay.setConfig(c),q.place(this._sourceDisplay.div(),this._detailsDiv),p.remove(this._detailsDiv,"hidden"),this._iCurrentSource=a))},_convertLayerIdToLayerName:function(a){var b=a;f.some(this._webmapFeatureLayers,function(c){return c.layerId===a?(b=c.name,!0):!1});return b},_convertLayerNameToLayerId:function(a){var b=a;f.some(this._webmapFeatureLayers,function(c){return c.name===a?(b=c.layerId,!0):!1});return b},_onChangeFeatureLayer:function(a){var b,
c=[];0<=this._iCurrentSource&&(b=this._config.sources[this._iCurrentSource],f.some(this._webmapFeatureLayers,e.hitch(this,function(d){return a===d.layerId?(b.name=d.layerId,b.searchFields=[],b.displayField=d.displayField,b.layerId=d.layerId,b.url=d.url,f.map(d.fields,function(a){c.push({label:a.alias||a.name,value:a.name})}),this._fieldListPicker.setFieldList(c),this._fieldListPicker.setDisplay(),this._displayFieldInput.setOptions(c),this._inputControl.renameTableRow(this._iCurrentSource,d.name),
!0):!1})))},_onChangeField:function(a){var b;0<=this._iCurrentSource&&(b=this._config.sources[this._iCurrentSource],b.displayField=a)},_onRowSelected:function(a){this._setDetails(a.rowIndex)},_onRowMoved:function(a,b){var c;this._removeCurrentDetails();c=b?a.rowIndex+1:a.rowIndex-1;b=this._sourceMenuItems.splice(c,1);c=this._config.sources.splice(c,1);this._sourceMenuItems.splice(a.rowIndex,0,b[0]);this._config.sources.splice(a.rowIndex,0,c[0]);this._inputControl.selectTableRow(a.rowIndex)},_onRowDeleted:function(a,
b,c){this._removeCurrentDetails();this._sourceMenuItems.splice(c,1);this._config.sources.splice(c,1);0<this._sourceMenuItems.length&&this._inputControl.selectTableRow(0)},_removeCurrentDetails:function(){var a;0<=this._iCurrentSource&&(p.add(this._detailsDiv,"hidden"),a=this._config.sources[this._iCurrentSource],this._sourceDisplay.getConfig(a),a.buffer.bufferUnitsMenu=r.labelsToUnitCodes(jimuNls.units,a.buffer.bufferUnitsMenu),"query"===a.type&&(a.name=this._convertLayerIdToLayerName(a.name)),q.empty(this._detailsDiv),
this._sourceDisplay=null,this._iCurrentSource=-1)}})});