// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/_base/declare ./BlankValueProvider ./SimpleValueProvider ./TwoNumbersValueProvider ./TwoDatesValueProvider ./ListValueProvider ./NumberListValueProvider ./DateIsInValueProvider jimu/utils jimu/LayerInfos/LayerInfos".split(" "),function(f,p,k,r,t,u,v,w,x,y,z,A){var l={stringOperatorIs:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",codedValueProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,supportCaseSensitive:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},
unique:{normalProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,filterCodedValueIfPossible:!0}},stringOperatorIsNot:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",codedValueProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,supportCaseSensitive:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,filterCodedValueIfPossible:!0}},stringOperatorStartsWith:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0,
supportCaseSensitive:!0}},stringOperatorEndsWith:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0,supportCaseSensitive:!0}},stringOperatorContains:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0,supportCaseSensitive:!0}},stringOperatorDoesNotContain:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0,supportCaseSensitive:!0}},stringOperatorIsBlank:{value:{normalProviderType:"BLANK_VALUE_PROVIDER"}},stringOperatorIsNotBlank:{value:{normalProviderType:"BLANK_VALUE_PROVIDER"}},
numberOperatorIs:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",codedValueProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,filterCodedValueIfPossible:!0}},numberOperatorIsNot:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",codedValueProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",
supportAskForValue:!0,filterCodedValueIfPossible:!0}},numberOperatorIsAtLeast:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,filterCodedValueIfPossible:!0}},numberOperatorIsLessThan:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",
supportAskForValue:!0,filterCodedValueIfPossible:!0}},numberOperatorIsAtMost:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",supportAskForValue:!0,filterCodedValueIfPossible:!0}},numberOperatorIsGreaterThan:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"},unique:{normalProviderType:"LIST_VALUE_PROVIDER",
supportAskForValue:!0,filterCodedValueIfPossible:!0}},numberOperatorIsBetween:{value:{normalProviderType:"TWO_NUMBERS_VALUE_PROVIDER",supportAskForValue:!0}},numberOperatorIsNotBetween:{value:{normalProviderType:"TWO_NUMBERS_VALUE_PROVIDER",supportAskForValue:!0}},numberOperatorIsBlank:{value:{normalProviderType:"BLANK_VALUE_PROVIDER"}},numberOperatorIsNotBlank:{value:{normalProviderType:"BLANK_VALUE_PROVIDER"}},dateOperatorIsOn:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},
field:{normalProviderType:"LIST_VALUE_PROVIDER"}},dateOperatorIsNotOn:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"}},dateOperatorIsIn:{value:{normalProviderType:"DATE_IS_IN_VALUE_PROVIDER",supportAskForValue:!0}},dateOperatorIsNotIn:{value:{normalProviderType:"DATE_IS_IN_VALUE_PROVIDER",supportAskForValue:!0}},dateOperatorIsBefore:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"}},
dateOperatorIsAfter:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"}},dateOperatorIsOnOrBefore:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"}},dateOperatorIsOnOrAfter:{value:{normalProviderType:"SIMPLE_VALUE_PROVIDER",supportAskForValue:!0},field:{normalProviderType:"LIST_VALUE_PROVIDER"}},dateOperatorInTheLast:{value:{normalProviderType:"NUMBER_LIST_VALUE_PROVIDER",
supportAskForValue:!0}},dateOperatorNotInTheLast:{value:{normalProviderType:"NUMBER_LIST_VALUE_PROVIDER",supportAskForValue:!0}},dateOperatorIsBetween:{value:{normalProviderType:"TWO_DATES_VALUE_PROVIDER",supportAskForValue:!0}},dateOperatorIsNotBetween:{value:{normalProviderType:"TWO_DATES_VALUE_PROVIDER",supportAskForValue:!0}},dateOperatorIsBlank:{value:{normalProviderType:"BLANK_VALUE_PROVIDER"}},dateOperatorIsNotBlank:{value:{normalProviderType:"BLANK_VALUE_PROVIDER"}}},d=k([],{nls:null,layerInfo:null,
popupInfo:null,url:null,layerDefinition:null,featureLayerId:null,constructor:function(a){f.mixin(this,a);this.nls=window.jimuNls.filterBuilder;a=A.getInstanceSync();this.featureLayerId&&(this.layerInfo=a.getLayerOrTableInfoById(this.featureLayerId))&&(this.popupInfo=this.layerInfo.getPopupInfo())},getSupportedValueTypes:function(a,c){var b=[];if(c=l[c])c.value&&b.push("value"),c.field&&0<this._getSameShortTypeFieldNames(a).length&&b.push("field"),c.unique&&this.url&&(this._isStreamServer(this.url)||
10.1<=parseFloat(this.layerDefinition.currentVersion)&&b.push("unique"));return b},_isStreamServer:function(a){a=(a||"").replace(/\/*$/g,"");return/\/StreamServer$/gi.test(a)},_getSameShortTypeFieldNames:function(a){var c=[],b=this._getFieldInfo(this.layerDefinition,a),g=d.getShortTypeByEsriType(b.type);p.forEach(this.layerDefinition.fields,f.hitch(this,function(b){b.name!==a&&d.getShortTypeByEsriType(b.type)===g&&c.push(b.name)}));return c},getValueProvider:function(a,c){var b=null,g=f.clone(l[a.operator]);
if(g){var d=a.valueObj.type,m=a.fieldObj.name,k=this._getFieldInfo(this.layerDefinition,m),h=g[d],e=h.normalProviderType,q=null,n=z.getCodedValueListForCodedValueOrSubTypes(this.layerDefinition,m);"field"===d?(d=this._getSameShortTypeFieldNames(m),0<d.length&&(q=p.map(d,f.hitch(this,function(a){return{value:a,label:a}})))):n&&0<n.length&&h.codedValueProviderType&&(e=h.codedValueProviderType);a={nls:this.nls,url:this.url,layerDefinition:this.layerDefinition,partObj:a,fieldInfo:k,codedValues:n,staticValues:q,
layerInfo:this.layerInfo,popupInfo:this.popupInfo,operatorInfo:g,filterCodedValueIfPossible:!!h.filterCodedValueIfPossible,runtime:c};"BLANK_VALUE_PROVIDER"===e?b=new r(a):"SIMPLE_VALUE_PROVIDER"===e?b=new t(a):"TWO_NUMBERS_VALUE_PROVIDER"===e?b=new u(a):"TWO_DATES_VALUE_PROVIDER"===e?b=new v(a):"LIST_VALUE_PROVIDER"===e?(a.showNullValues=!1,b=new w(a)):"NUMBER_LIST_VALUE_PROVIDER"===e?b=new x(a):"DATE_IS_IN_VALUE_PROVIDER"===e&&(b=new y(a))}return b},_getFieldInfo:function(a,c){a=a.fields;for(var b=
0;b<a.length;b++){var d=a[b];if(c===d.name)return d}return null}});d.getOperatorInfo=function(a){return f.clone(l[a])};d.getOperatorsByShortType=function(a,c){var b=[];"string"===a?b="stringOperatorIs stringOperatorIsNot stringOperatorStartsWith stringOperatorEndsWith stringOperatorContains stringOperatorDoesNotContain stringOperatorIsBlank stringOperatorIsNotBlank".split(" "):"number"===a?b="numberOperatorIs numberOperatorIsNot numberOperatorIsAtLeast numberOperatorIsLessThan numberOperatorIsAtMost numberOperatorIsGreaterThan numberOperatorIsBetween numberOperatorIsNotBetween numberOperatorIsBlank numberOperatorIsNotBlank".split(" "):
"date"===a&&(b="dateOperatorIsOn dateOperatorIsNotOn dateOperatorIsIn dateOperatorIsNotIn dateOperatorIsBefore dateOperatorIsAfter dateOperatorIsOnOrBefore dateOperatorIsOnOrAfter dateOperatorIsBetween dateOperatorIsNotBetween dateOperatorIsBlank dateOperatorIsNotBlank".split(" "),c&&b.splice(8,0,"dateOperatorInTheLast","dateOperatorNotInTheLast"));return b};d.getShortTypeByEsriType=function(a){var c=null;"esriFieldTypeString"===a?c="string":"esriFieldTypeDate"===a?c="date":0<=["esriFieldTypeOID",
"esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"].indexOf(a)&&(c="number");return c};return d});