// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/Deferred dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on jimu/utils esri/geometry/geometryEngine esri/graphic esri/Color esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query ./analysisUtils".split(" "),function(N,p,H,O,I,D,q,x,P,J,C,Q,K,F,R,y,L,M,S,T,U,u){return N("ClosestInfo",null,
{featureCount:0,mapServiceLayer:!1,loading:!1,queryOnLoad:!1,incidentCount:0,constructor:function(a,c,d){this.tab=a;this.container=c;this.parent=d;this.graphicsLayer=this.incident=null;this.map=d.map;this.specialFields={};this.typeIdField="";this.types=[];this.dateFields={};this.config=d.config;this.baseLabel=""!==a.label?a.label:a.layerTitle?a.layerTitle:a.layers},queryTabCount:function(a,c,d,f){var l=new D;this.incidentCount=a.length;var e=this.parent.config.distanceSettings[this.parent.config.distanceUnits],
m=this.parent.config.maxDistance;c=[];for(var h=0;h<a.length;h++)c.push(K.buffer(a[h].geometry,m,e));var b=[this.tab.tabLayers[0]];this.mapServiceLayer&&1<this.tab.tabLayers.length&&(b=[this.tab.tabLayers[1]]);if(0<this.tab.tabLayers.length&&this.tab.tabLayers[0].url&&-1<this.tab.tabLayers[0].url.indexOf("MapServer")){this.mapServiceLayer=!0;var k;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],this.summaryLayer.hasOwnProperty("loaded")&&this.summaryLayer.loaded?
(this.summaryFields=this._getFields(this.summaryLayer),this._performQuery(a,c,d,f,b).then(function(a){l.resolve(a)})):(k=new y(this.summaryLayer.url),k.infoTemplate=this.tab.tabLayers[0].infoTemplate,b=[k],this.tab.tabLayers=b,C(k,"load",p.hitch(this,function(){this.summaryLayer=k;this.summaryFields=this._getFields(this.summaryLayer);this._performQuery(a,c,d,f,b).then(function(a){l.resolve(a)})})))):this.loading||(k=new y(this.tab.tabLayers[0].url),this.loading=!0,C(k,"load",p.hitch(this,function(){this.summaryLayer=
k;this.summaryFields=this._getFields(this.summaryLayer);for(var g=this.tab.tabLayers[0].url.split("MapServer/")[1],e=this.parent.map.itemInfo.itemData.operationalLayers,t=0;t<e.length;t++){var h=e[t];if("undefined"!==typeof h.layerObject&&h.layerObject.infoTemplates&&(h=h.layerObject.infoTemplates[g])){k.infoTemplate=h.infoTemplate;break}}b=[k];this.tab.tabLayers=b;this.loading=!1;this._performQuery(a,c,d,f,b).then(function(a){l.resolve(a)})})))}this.mapServiceLayer||this._performQuery(a,c,d,f,b).then(function(a){l.resolve(a)});
return l},_performQuery:function(a,c,d,f,l){var e=new D,m=[],h,b;this.summaryGeoms=c;if(0<c.length)for(a=0;a<c.length;a++)m=c[a],b=u.createDefArray(l,m,this.parent.opLayers,this.tab),h=0===a?m=b:m=h.concat(b);(new I(m)).then(p.hitch(this,function(a){for(var g=0,c=0;c<a.length;c++){var b=a[c][1];isNaN(b)?b&&b.features?0<b.features.length&&(g+=1):b&&"undefined"!==typeof b.length&&0<b.length&&(g+=1):0<b&&(g+=1)}this.updateTabCount(g,d,f);e.resolve(g)}));return e},updateTabCount:function(a,c,d){this.featureCount=
0===parseInt(a,10)?0:a;u.updateTabCount(this.featureCount,c,d,this.baseLabel,this.incidentCount)},updateForIncident:function(a,c,d,f,l,e){this.incidentCount=a.length;this.allFields="undefined"!==typeof l&&"undefined"!==typeof e?l?!0:e:!1;var m="undefined"!==typeof f,h;O.forEach(this.tab.tabLayers,p.hitch(this,function(b){m&&(h=new D);if(b.url){var e=new y(b.url,{mode:y.MODE_ONDEMAND,infoTemplate:b.infoTemplate});C(e,"load",p.hitch(this,function(){this.tab.tabLayers=[e];m?this.processIncident(a,c,
d,f).then(p.hitch(this,function(a){h.resolve(a)}),p.hitch(this,function(a){console.error(a);h.reject(a)})):this.processIncident(a,c,d,f)}))}else m?this.processIncident(a,c,d,f).then(p.hitch(this,function(a){h.resolve(a)}),p.hitch(this,function(a){console.error(a);h.reject(a)})):this.processIncident(a,c,d,f)}));if(m)return h},processIncident:function(a,c,d,f){this.incidents=a;var l,e="undefined"!==typeof f;e?l=new D:(this.container.innerHTML="",q.add(this.container,"loading"));var m=[];f=this.parent.config.distanceSettings[this.parent.config.distanceUnits];
for(var h=[],b=0;b<a.length;b++){var k=a[b].geometry,g=K.buffer(k,c,f);h.push({geometry:k,buffer:g})}(this.graphicsLayer=d)&&this.graphicsLayer.clear();a=[];c=this.tab.tabLayers[0];d=-1===[null,void 0,""].indexOf(c.id)?c.id:this.tab.layers;d=u.getFilter(d,this.parent.opLayers);var r=this._getFields(c);for(f=0;f<h.length;f++)b=new U,b.returnGeometry=!0,b.outSpatialReference=this.parent.map.spatialReference,b.geometry=h[f].buffer,b.where=d,b.outFields="true"===this.parent.config.csvAllFields||!0===
this.parent.config.csvAllFields?["*"]:r,"undefined"!==typeof c.queryFeatures&&a.push(c.queryFeatures(b));(new I(a)).then(p.hitch(this,function(a){for(var b=0;b<a.length;b++)if(a[b][0]){var c=a[b][1].features,d=[],f=h[b].geometry;if(c&&0<c.length){for(var g=0;g<c.length;g++){for(var k=new F(c[g].toJson()),q=u.getDistance(f,k.geometry,this.parent.config.distanceUnits),n={DISTANCE:q},t=0;t<r.length;t++)n[r[t]]=k.attributes[r[t]];!0===this.config.csvAllFields||"true"===this.config.csvAllFields?k.attributes.DISTANCE=
q:k.attributes=n;d.push(k)}d.sort(u.compareDistance);m.push(d[0])}}else a[b][1]&&a[b][1].message&&console.log(a[b][1].message);m.sort(u.compareDistance);e?this._processResults(m,!0).then(p.hitch(this,function(a){l.resolve(a)})):this._processResults(m)}),p.hitch(this,function(a){console.error(a);l.reject(a)}));if(e)return l},_processResults:function(a,c){var d,f,l=a&&0<a.length;if(l&&"point"!==a[0].geometry.type)for(var e=a.length-1;0<=e;e--)"undefined"===typeof a[e].geometry.getExtent()&&a.splice(e,
1);c?d=new D:(this.container.innerHTML="",q.remove(this.container,"loading"),l&&(f=x.create("div",{"class":"SAT_tabPanelContent"},this.container),e=x.create("div",{},f),q.add(e,"SATcolExport"),q.add(e,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),e=x.create("div",{title:this.parent.nls.downloadCSV},e),q.add(e,"btnExport"),C(e,"click",p.hitch(this,this._exportToCSV,a))));var e=this.parent.nls[this.parent.config.distanceUnits],m=[],h=220;if(l)for(var b=0;b<a.length;b++){var k=b+1,g=a[b],
r=g.geometry,t=r;"point"!==r.type&&(t=r.getExtent().getCenter());var r=g.attributes,y;"point"===this.incidents[0].geometry.type&&(y=Math.round(100*r.DISTANCE)/100+" "+e+" ("+this.parent.nls.approximate+")");var z="",w=0,A=[];if("undefined"!==typeof this.displayFields)for(var G=0;G<this.displayFields.length;G++){var v=this.displayFields[G],B;a:for(B in r)if("DISTANCE"!==B&&3>w&&v.expression===B){var n=u.getFieldValue(B,r[B],this.specialFields,this.dateFields,"longMonthDayYear",this.typeIdField,this.types),
n="undefined"!==typeof n&&null!==n?Q.stripHTML(n.toString()):"",v="undefined"!==typeof v.label?v.label:void 0,E=g._layer&&g._layer.fields?g._layer.fields:this.tab.tabLayers&&this.tab.tabLayers[0]?this.tab.tabLayers[0].fields:void 0;E&&(E=u.getField(E,B))&&(v=E.alias);if("undefined"===typeof v||v in[""," ",null,void 0])v=B;u.isURL(n)?n='\x3ca href\x3d"'+n+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+v+"\x3c/a\x3e":u.isEmail(n)&&(n='\x3ca href\x3d"mailto:'+n+'" style\x3d"color: inherit;"\x3e'+
v+"\x3c/a\x3e");z+=n+"\x3cbr/\x3e";w+=1;A.push({value:-1<n.indexOf(",")?n.replace(",",""):n,label:v});break a}}m.push(A);c||(g=x.create("div",{},f),q.add(g,"SATcolRec"),q.add(g,this.parent.lightTheme?"lightThemeBorder":"darkThemeBorder"),w=x.create("div",{},g),q.add(w,"SATcolRecBar"),A=x.create("div",{innerHTML:k},w),q.add(A,"SATcolRecNum"),J.set(A,"backgroundColor",this.parent.config.activeColor),C(A,"click",p.hitch(this,this._zoomToLocation,t)),y&&(A=x.create("div",{innerHTML:y},w),q.add(A,"SATcolDistance")),
this.parent.config.enableRouting&&(w=x.create("div",{title:this.parent.nls.get_directions},w),q.add(w,"SATcolDir"),C(w,"click",p.hitch(this,this._routeToIncident,t))),z=x.create("div",{"class":"SATcolWrap",innerHTML:z},g),q.add(z,"SATcolInfo"),h+=P.position(g).w,z=new M(M.STYLE_SOLID,new H.fromRgb(this.parent.config.activeMapGraphicColor),1),z=new L(L.STYLE_CIRCLE,24,z,new H.fromRgb(this.parent.config.activeMapGraphicColor)),g=new S,g.family="Arial",g.size="12px",k=new T(k,g,new R(this.parent.config.fontColor)),
k.setOffset(0,-4),this.graphicsLayer.add(new F(t,z,r)),this.graphicsLayer.add(new F(t,k,r)))}if(!c&&l)J.set(f,"width",h);else if(l)return d.resolve({graphics:a,analysisResults:m,context:this}),d},_exportToCSV:function(a,c,d,f){a=u.exportToCSV(a,c,d,f,{type:"closest",baseLabel:this.baseLabel,csvAllFields:this.parent.config.csvAllFields,layer:this.tab.tabLayers[0],opLayers:this.parent.opLayers,nlsValue:this.parent.nls.closest,nlsCount:this.parent.nls.count});this.summaryLayer=a.summaryLayer;return a.details},
_getFields:function(a){a=u.getFields(a,this.tab,this.allFields,this.parent);this.dateFields=a.dateFields;this.specialFields=a.specialFields;this.typeIdField=a.typeIdField;this.types=a.types;this.displayFields=u.getDisplayFields(this.tab);return a.fields},_zoomToLocation:function(a){this.parent.zoomToLocation(a)},_routeToIncident:function(a){this.parent.routeToIncident(a)}})});