// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/Infographic/setting/dijitsSetting/NumberDijitSetting.html":'\x3cdiv\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"settingTitle" class\x3d"flex-lc text-label settingTitle"\x3e${nls.numberSettings}\x3c/div\x3e\r\n  \x3cdiv class\x3d"infohraphic-setting-tab-container" style\x3d"width:100%;"\x3e\r\n    \x3cdiv style\x3d"margin-top: 20px;" data-dojo-attach-point\x3d"tabNode" class\x3d"tabHeader"\x3e\x3c/div\x3e\r\n\r\n    \x3cdiv style\x3d"margin-top: 10px;" data-dojo-attach-point\x3d"numberStatistics"\x3e\x3c/div\x3e\r\n\r\n    \x3cdiv style\x3d"margin-top: 10px;" class\x3d"number-setting-display paddingRight10" data-dojo-attach-point\x3d"display"\x3e\r\n      \x3cdiv class\x3d"section"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"dataFormatSettingNode"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv class\x3d"section"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"fontSettingNode"\x3e\r\n      \x3c/div\x3e\r\n      \x3cdiv class\x3d"section"\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"backgroundSettingNode"\x3e\r\n      \x3c/div\x3e\r\n    \x3c/div\x3e\r\n\r\n    \x3cdiv style\x3d"margin-top: 20px;" class\x3d"indicatorsTitlePane paddingRight10" data-dojo-attach-point\x3d"indicatorsDiv"\x3e\x3c/div\x3e\r\n\r\n  \x3c/div\x3e\r\n\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin dojo/text!./NumberDijitSetting.html ./BaseDijitSetting dijit/_TemplatedMixin ./_dijits/NumberIndicator/MultipleIndicators ./_dijits/SingleNumberStatistics ./_dijits/BackgroundSetting ./_dijits/FontSetting ./_dijits/DataFormatSetting dojo/_base/lang dojo/on jimu/dijit/TabContainer3 jimu/dijit/Message dijit/TitlePane".split(" "),function(d,e,f,g,h,k,l,m,n,p,b,c,q,r){return d([g,e,h],{templateString:f,baseClass:"infographic-number-dijit-setting",
type:"number",postMixInProperties:function(){b.mixin(this.nls,window.jimuNls.common)},postCreate:function(){this.inherited(arguments);this._initUI();this.setConfig(this.config);this._hasLoaded=!0},isValid:function(a){return!this.indicators.getConfig(a)&&a?(this.tab.selectTab(this.nls.indicators),new r({message:this.nls.setCorrectyIndicatorTip}),!1):this.backgroundSetting.isValid()&&this.fontSetting.isValid()&&this.dataFormatSetting.isValid()&&this.singleNumberStatistics.isValid()},getConfig:function(a){this.config||
(this.config={});return this.isValid(a)?(this.config.indicators=this.indicators.getConfig(),this.backgroundSetting&&(this.config.background=this.backgroundSetting.getConfig()),this.fontSetting&&(this.config.font=this.fontSetting.getConfig()),this.dataFormatSetting&&(this.config.dataFormat=this.dataFormatSetting.getConfig()),this.singleNumberStatistics&&(this.config.statistic=this.singleNumberStatistics.getConfig()),this.config):!1},setConfig:function(a){if(this.config=a)this.indicators.setConfig(this.config),
this.singleNumberStatistics.setConfig(this.config.statistic)},updateDijit:function(){this.dijit.setConfig(this.config)},_initUI:function(){this._initTabs();this._initIndicators();this._initSingNumberStatistics();this._initDisplay()},_initTabs:function(){this.tab=new q({average:!0,tabs:[{title:this.nls.data,content:this.numberStatistics},{title:this.nls.display,content:this.display},{title:this.nls.indicators,content:this.indicatorsDiv}]},this.tabNode)},_initDisplay:function(){this.backgroundSetting=
new m({config:this.config.background,nls:this.nls});this.backgroundSetting.placeAt(this.backgroundSettingNode);this.backgroundSetting.startup();this.own(c(this.backgroundSetting,"change",b.hitch(this,function(){this._onSettingsChange()})));this.fontSetting=new n({config:this.config.font,nls:this.nls});this.fontSetting.placeAt(this.fontSettingNode);this.fontSetting.startup();this.own(c(this.fontSetting,"change",b.hitch(this,function(){this._onSettingsChange()})));this.dataFormatSetting=new p({config:this.config.dataFormat,
nls:this.nls});this.dataFormatSetting.placeAt(this.dataFormatSettingNode);this.dataFormatSetting.startup();this.own(c(this.dataFormatSetting,"change",b.hitch(this,function(){this._onSettingsChange()})))},_initSingNumberStatistics:function(){this.singleNumberStatistics=new l({config:this.config.statistic,dataSource:this.dataSource,nls:this.nls});this.singleNumberStatistics.placeAt(this.numberStatistics);this.singleNumberStatistics.startup();this.own(c(this.singleNumberStatistics,"change",b.hitch(this,
function(a){var b=this.dataFormatSetting.getConfig(),c=b.decimalPlaces;if(a&&"Features"===a.type){if("number"!==typeof c||2===c)b.decimalPlaces=0,this.dataFormatSetting.setConfig(b)}else!a||"FeatureStatistics"!==a.type||"number"===typeof c&&0!==c||(b.decimalPlaces=2,this.dataFormatSetting.setConfig(b));this._onSettingsChange()})))},_initIndicators:function(){this.indicators=new k({nls:this.nls,type:"number",folderUrl:this.folderUrl});this.indicators.placeAt(this.indicatorsDiv);this.indicators.startup();
this.own(c(this.indicators,"change",b.hitch(this,function(){this._onSettingsChange()})))},_onSettingsChange:function(){this._hasLoaded&&(this.getConfig(),this.updateDijit())},setDataSource:function(a){this.inherited(arguments);this.singleNumberStatistics&&this.singleNumberStatistics.setDataSource(a)},destroy:function(){this.indicators&&(this.indicators.destroy(),this.indicators=null);this.singleNumberStatistics&&(this.singleNumberStatistics.destroy(),this.singleNumberStatistics=null);this.inherited(arguments)}})});