// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/_base/html dojo/dom-construct dijit/_TemplatedMixin dijit/_WidgetBase".split(" "),function(h,e,f,d,b,k,l){return h([l,k],{name:"FilterEditor",baseClass:"jimu-widget-FilterEditor",declaredClass:"jimu.dijit.FilterEditor",templateString:"\x3cdiv style\x3d'width:100%'\x3e\x3cdiv data-dojo-attach-point\x3d'filterEditorDiv'\x3e\x3c/div\x3e\x3c/div\x3e",_settings:null,_editWidget:null,_origGetItemsFromLayerFunc:null,postCreate:function(){this.nls=
this._editWidget.nls;this._createFilterTool()},_createFilterTool:function(){var c=b.create("label",{innerHTML:this.nls.featureLayers});b.place(c,this.filterEditorDiv);this._createLayerFilter();this._createTemplateFilter()},_createLayerFilter:function(){this.selectDropDown=b.create("select",{"class":"jimu-input flDropDown"});b.place(this.selectDropDown,this.filterEditorDiv);this.selectDropDown.onchange=e.hitch(this,function(){this._onLayerFilterChanged()});var c=b.create("option",{value:"all",innerHTML:window.jimuNls.common.all});
b.place(c,this.selectDropDown);for(var a,c=0;c<this._editWidget._layerObjectsParaForTempaltePicker.length;c++)a=this._editWidget._layerObjectsParaForTempaltePicker[c],a=b.create("option",{value:a.id,innerHTML:a.name}),b.place(a,this.selectDropDown)},_createTemplateFilter:function(){this.filterTextBox=b.create("input",{"class":"jimu-input searchtextbox",type:"text",placeholder:this.nls.searchTemplates},this.filterEditorDiv);this.filterTextBox.onkeyup=e.hitch(this,function(){this._onTempalteFilterChanged()});
var c=this._editWidget.editor.templatePicker;this._origGetItemsFromLayerFunc=c._getItemsFromLayer;c._getItemsFromLayer=e.hitch(this,function(){var a;a=this._origGetItemsFromLayerFunc.apply(c,arguments);var g=this.filterTextBox.value;g&&(a=f.filter(a,function(a){var c=!1,b=new RegExp(g,"ig");a.hasOwnProperty("label")&&a.label.match(b)&&0<a.label.match(b).length&&(c=!0);a.hasOwnProperty("template")&&a.template.hasOwnProperty("name")&&a.template.name.match(b)&&0<a.template.name.match(b).length&&(c=!0);
return c}));0===a.length&&(this._editWidget.editor.templatePicker.grid.noDataMessage=this.nls.noAvailableTempaltes);return a})},show:function(){d.setStyle(this.domNode,"display","block")},hide:function(){d.setStyle(this.domNode,"display","none")},selectLayerFilterByValue:function(c){f.forEach(this.selectDropDown.options,function(a,b){a.value===c&&(this.selectDropDown.selectedIndex=b)},this)},setTemplateFilter:function(c){this.filterTextBox.value=c},disableLayerFilter:function(){d.setAttr(this.selectDropDown,
"disabled",!0)},enableLayerFilter:function(){d.setAttr(this.selectDropDown,"disabled",!1)},_onLayerFilterChanged:function(c){var a=this._editWidget.editor.templatePicker;a.clearSelection();var b=this.selectDropDown.options[this.selectDropDown.selectedIndex].text;""!==b&&("All"===b?(a.attr("featureLayers",this._editWidget._layerObjectsParaForTempaltePicker),""===this.filterTextBox.value?a.attr("grouping",!0):a.attr("grouping",!1)):(b=this._editWidget.map.getLayer(this.selectDropDown.value),a.attr("featureLayers",
[b]),a.attr("grouping",!1)),c&&a.attr("grouping",!0),a.update(!0))},_onTempalteFilterChanged:function(c){var a=this.selectDropDown.options[this.selectDropDown.selectedIndex].text,b=this.filterTextBox.value;this._editWidget.editor.templatePicker.clearSelection();"All"===a&&""===b?this._editWidget.editor.templatePicker.attr("grouping",!0):this._editWidget.editor.templatePicker.attr("grouping",!1);c&&this._editWidget.editor.templatePicker.attr("grouping",!0);this._editWidget.editor.templatePicker.update(!0)}})});