// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["jimu/shared/BaseVersionManager"],function(m){function k(){this.versions=[{version:"1.0",upgrader:function(a){return a}},{version:"1.1",upgrader:function(a){return a}},{version:"1.2",upgrader:function(a){return a}},{version:"1.3",upgrader:function(a){return a}},{version:"1.4",upgrader:function(a){return a}},{version:"2.0Beta",upgrader:function(a){return a}},{version:"2.0",upgrader:function(a){return a}},{version:"2.0.1",upgrader:function(a){return a}},{version:"2.1",upgrader:function(a){return a}},
{version:"2.2",upgrader:function(a){return a}},{version:"2.3",upgrader:function(a){return a}},{version:"2.4",upgrader:function(a){return a}},{version:"2.5",upgrader:function(a){return a}},{version:"2.6",upgrader:function(a){for(var d=a.dijits,c,b=0;b<d.length;b++)"chart"===d[b].type&&(c=d[b].config.sortOrder,d[b].config.sortOrder={isLabelAxis:!0,isAsc:c?"asc"===c:!0},"feature"===d[b].config.mode&&(d[b].config.sortOrder.field=d[b].config.labelField),d[b].config.maxLabels=void 0,d[b].config.nullValue=
"feature"===d[b].config.mode||"count"===d[b].mode?void 0:!0,d[b].config.dateConfig=void 0,d[b].config.useLayerSymbology=void 0);return a}},{version:"2.7",upgrader:function(a){for(var d=a.dijits,c,b=0;b<d.length;b++)if("chart"===d[b].type){c=d[b].config;break}if(!c||!c.mode)return a;var d=c.mode,b=c.type,f=c.valueFields,l=c.colors;l||(l="#5d9cd3 #eb7b3a #a5a5a5 #febf29 #4673c2 #72ad4c".split(" "));var h={};"undefined"!==typeof c.useLayerSymbology&&"line"===b&&delete c.useLayerSymbology;"undefined"!==
typeof c.useLayerSymbology&&(h.useLayerSymbology=c.useLayerSymbology);var g=[];f&&0<f.length&&(g=f);var e=!1;"column"===b||"bar"===b||"line"===b?"line"===b&&"field"===d?g=["line~field"]:"count"===d&&(g=["count~count"]):"pie"===b&&"field"!==d&&(e=!0,g=["pie~not-field"]);f=g.map(function(a,b){var d=l;a={name:a,style:{color:d[b%d.length]}};e&&(a.style.color=d);return a}.bind(this));h.styles={};f&&(h.styles=f);c.seriesStyle=h;"undefined"!==typeof c.colors&&delete c.colors;"pie"===b||"count"!==d&&"field"!==
d||(c.showLegend=!1);"pie"===b&&c.dateConfig&&(c.dateConfig.isNeedFilled=!1);return a}},{version:"2.8",upgrader:function(a){var d=a.dijits.filter(function(a){return"chart"===a.type})[0];if(!d)return a;var c=d&&d.config;if(!c||!c.mode)return a;var b=c.seriesStyle;if(!b)return a;b.type=b.useLayerSymbology?"layerSymbol":"series";"undefined"!==typeof b.useLayerSymbology&&delete b.useLayerSymbology;d.config=function(a){var b={mode:a.mode,type:a.type},d=b.type,c=b.mode,e=[];"feature"===c?e=e.concat(["labelField",
"valueFields","sortOrder","maxLabels"]):"category"===c?e=e.concat("categoryField dateConfig valueFields sortOrder operation maxLabels nullValue".split(" ")):"count"===c?e=e.concat(["categoryField","dateConfig","sortOrder","maxLabels"]):"field"===c&&(e=e.concat(["valueFields","operation","sortOrder","maxLabels","nullValue"]));c="backgroundColor seriesStyle showLegend legendTextColor legendTextSize highLightColor".split(" ");c="pie"===d?c.concat(["showDataLabel","dataLabelColor","dataLabelSize","innerRadius"]):
c.concat("showHorizontalAxis horizontalAxisTextColor horizontalAxisTextSize showVerticalAxis verticalAxisTextColor verticalAxisTextSize stack area".split(" "));e.forEach(function(c){b[c]=a[c]});c.forEach(function(c){b[c]=a[c]});b.hasOwnProperty("showLegend")||(b.showLegend=!1);"pie"===d?b.hasOwnProperty("showDataLabel")||(b.showDataLabel=!0):(b.hasOwnProperty("showHorizontalAxis")||(b.showHorizontalAxis=!0),b.hasOwnProperty("showVerticalAxis")||(b.showVerticalAxis=!0));return b}(c);return a}}]}k.prototype=
new m;return k.prototype.constructor=k});