// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/NearMe/filter-list.html":'\x3cdiv\x3e\r\n  \x3cul class\x3d"filter-list" data-dojo-attach-point\x3d"filterList"\x3e\x3c/ul\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/text!./filter-list.html dojo/_base/array dojo/_base/html dojo/_base/lang dojo/query dojo/on dijit/_WidgetsInTemplateMixin dojo/dom-class jimu/utils jimu/BaseWidget jimu/filterUtils jimu/dijit/FilterParameters jimu/LayerInfos/LayerInfos jimu/FilterManager esri/request dojo/NodeList dojo/NodeList-dom".split(" "),function(n,p,k,g,d,h,m,q,l,r,t,u,v,w,x,y){return n([t,q],{name:"NearMeFilter",templateString:p,baseClass:"jimu-widget-nearme-filter",_itemTemplate:'\x3cli class\x3d"filter-item" data-index\x3d"${index}"\x3e\x3cdiv class\x3d"header jimu-leading-padding1" \x3e\x3cspan class\x3d"arrow jimu-float-leading jimu-trailing-margin05" title\x3d"${toggleTip}" \x3e\x3c/span\x3e\x3cspan class\x3d"icon"\x3e\x3cimg src\x3d"${icon}" /\x3e\x3c/span\x3e\x3cspan class\x3d"item-title"\x3e${title}\x3c/span\x3e\x3cspan class\x3d"cando jimu-float-trailing jimu-leading-margin1 jimu-trailing-margin1 "\x3e\x3c/span\x3e\x3cspan class\x3d"doing jimu-float-trailing jimu-leading-margin1 jimu-trailing-margin1 "\x3e\x3c/span\x3e\x3cspan class\x3d"done jimu-float-trailing jimu-leading-margin1 jimu-trailing-margin1 "\x3e\x3c/span\x3e\x3c/div\x3e\x3cdiv class\x3d"body"\x3e\x3cdiv class\x3d"parameters"\x3e\x3c/div\x3e\x3cspan class\x3d"jimu-btn apply jimu-float-trailing jimu-trailing-margin25"\x3e${apply}\x3c/span\x3e\x3c/div\x3e\x3c/li\x3e',
_layerTitleTemplate:'\x3cdiv class\x3d"esriCTGroupFilterLayerName"\x3e${layerTitle}\x3c/div\x3e',_store:null,totalAppliedFilters:0,postCreate:function(){this.inherited(arguments);this.totalAppliedFilters=0;this._updateClearAllButtonState();this.own(m(this.clearAllButton,"click",d.hitch(this,this._clearAllFilters)));this._store={};this.layerInfosObj=w.getInstanceSync();this.filterUtils=new u;this.filterManager=x.getInstance();var a=this.config.filters,b={},c=[];this.config.groupFiltersByLayer?(k.forEach(a,
function(a,f){b[a.layerId]||(b[a.layerId]=[],c.push(a.layerId));a.index=f;b[a.layerId].push(a)}),k.forEach(c,d.hitch(this,function(a){var c={layerTitle:this.layerInfosObj.getLayerInfoById(a).layerObject.name},c=d.replace(this._layerTitleTemplate,c,/\$\{([^\}]+)\}/ig),c=g.toDom(c);g.place(c,this.filterList);for(c=0;c<b[a].length;c++)this._addFilterInList(b[a][c],b[a][c].index)}))):k.forEach(a,d.hitch(this,function(a,b){this._addFilterInList(a,b)}))},_addFilterInList:function(a,b){var c=this.filterUtils.isAskForValues(a.filter);
b={icon:a.icon?r.processUrlInWidgetConfig(a.icon,this.folderUrl):this.folderUrl+"/css/images/default_task_icon.png",index:b,title:a.name,toggleTip:this.nls.toggleTip,hasValue:c?window.appInfo.isRunInMobile?"block !important":"":"none",isAskForValue:c,apply:d.getObject("jimuNls.common.apply",!1,window)||"Apply"};this._store[a.layerId]||(this._store[a.layerId]={mapFilterControls:{}});var e=d.replace(this._itemTemplate,b,/\$\{([^\}]+)\}/ig),f=g.toDom(e);g.place(f,this.filterList);this.own(h(".header",
f).on("click",d.hitch(this,"enableFilter",f,a,b)));c?g.addClass(f,"has-ask-for-value"):g.addClass(f,"not-has-ask-for-value");"none"!==b.hasValue&&(this.own(h(".arrow",f).on("click",d.hitch(this,"configFilter",f,a))),this.own(h(".apply",f).on("click",d.hitch(this,"applyFilterValues",f,a))),g.addClass(f,"requesting"),this.configFilter(f,a,null,d.hitch(this,function(){this.config.collapse&&g.removeClass(f,"config-parameters")})))},startup:function(){this.inherited(arguments);this.resize()},_getPriorityOfMapFilter:function(a){a=
d.getObject(a+".mapFilterControls",!1,this._store);var b=0,c;for(c in a){var e=a[c];e.priority>b&&(b=e.priority)}return b},_getMapFilterControl:function(a){a=d.getObject(a+".mapFilterControls",!1,this._store);var b=!0,c;for(c in a){var e=a[c];0<e.priority&&(b=!!e.enable)}return b},_setItemFilter:function(a,b,c,e){this._store[a]["filter_item_"+b]=c;c=this._getPriorityOfMapFilter(a);d.setObject(a+".mapFilterControls.filter_item_"+b,{enable:e,priority:c+1},this._store)},_removeItemFilter:function(a,
b){delete this._store[a]["filter_item_"+b];delete this._store[a].mapFilterControls["filter_item_"+b]},_getExpr:function(a){if(!this._store[a])return null;var b=[];a=this._store[a];for(var c in a){var e=a[c];e&&"mapFilterControls"!==c&&b.push("("+e+")")}return b.join(" AND ")},_bindMapUpdateEvents:function(a,b){m.once(this.map,"update-start",d.hitch(this,function(){g.addClass(a,"applying");g.removeClass(a,"applied")}));m.once(this.map,"update-end",d.hitch(this,function(){b?g.addClass(a,"applied"):
g.removeClass(a,"applied");g.removeClass(a,"applying")}))},enableFilter:function(a,b,c){if(!g.hasClass(a,"config-parameters")||a.filterParams&&a.filterParams.getFilterExpr())if(!c.isAskForValue||a.filterParams&&a.filterParams.getFilterExpr()){c=b.layerId;var e=g.getAttr(a,"data-index"),f=null,d=this.layerInfosObj.getLayerInfoById(c),f=g.hasClass(a,"applied");d.isShowInMap()&&d.isInScale()?this._bindMapUpdateEvents(a,f?!1:!0):f?g.removeClass(a,"applied"):g.addClass(a,"applied");d=null;f?(this._removeItemFilter(c,
e),f=this._getExpr(c),d=this._getMapFilterControl(c),this.filterManager.applyWidgetFilter(c,this.id,f,d),this.totalAppliedFilters--):(this._setItemFilter(c,e,a.filterParams?a.filterParams.getFilterExpr():b.filter.expr,b.enableMapFilter),f=this._getExpr(c),d=this._getMapFilterControl(c),this.filterManager.applyWidgetFilter(c,this.id,f,d),this.totalAppliedFilters++);this.filtersUpdated=!0;this._updateClearAllButtonState()}else this.configFilter(a,b)},configFilter:function(a,b,c,e){a.filterParams?(g.hasClass(a,
"config-parameters")?(g.removeClass(a,"config-parameters"),this._changeItemTitleWidth(a,window.appInfo.isRunInMobile?60:45)):(g.addClass(a,"config-parameters"),this._changeItemTitleWidth(a,60)),e&&e()):y({url:b.url,content:{f:"json"},handleAs:"json",callbackPrams:"callback"}).then(d.hitch(this,function(c){g.addClass(a,"config-parameters");g.removeClass(a,"requesting");var f=h(".parameters",a)[0];a.handles=[];a.filterParams=new v;var k=d.clone(b.filter),l=null;b.enableMapFilter&&(l=b.layerId);a.filterParams.build(b.url,
c,k,l);this.own(m(a.filterParams,"change",d.hitch(this,function(b){b?(h(".apply",a).removeClass("disable-apply"),a.expr=b):(delete a.expr,h(".apply",a).addClass("disable-apply"))})));a.expr=a.filterParams.getFilterExpr();a.expr?h(".apply",a).removeClass("disable-apply"):(delete a.expr,h(".apply",a).addClass("disable-apply"));a.filterParams.placeAt(f);this._changeItemTitleWidth(a,60);e&&e()}));c&&c.target&&c.stopPropagation()},applyFilterValues:function(a,b,c){var e=a.filterParams&&(a.expr||a.filterParams.getFilterExpr());
if(e){a.expr=e;var e=b.layerId,f=g.getAttr(a,"data-index"),d=this.layerInfosObj.getLayerInfoById(e);d.isShowInMap()&&d.isInScale()?this._bindMapUpdateEvents(a,!0):g.addClass(a,"applied");this._setItemFilter(e,f,a.expr,b.enableMapFilter);a=this._getExpr(e);b=this._getMapFilterControl(e);this.filterManager.applyWidgetFilter(e,this.id,a,b);this.filtersUpdated=!0;this.totalAppliedFilters++;this._updateClearAllButtonState()}c.stopPropagation()},resize:function(){this.inherited(arguments);this._changeItemTitleWidth(this.domNode,
window.appInfo.isRunInMobile?60:45)},_changeItemTitleWidth:function(a,b){var c=h(".header",a)[0];c&&(b=g.getContentBox(c).w-b,0<b&&h(".header .item-title",a).style({maxWidth:b+"px"}))},destroy:function(){h(".filter-item",this.filterList).forEach(function(a){delete a.filterParams;delete a.expr});if(this._store)for(var a in this._store)a&&this.filterManager.applyWidgetFilter(a,this.id,"",null);this.inherited(arguments)},filterListShown:function(){this.filtersUpdated=!1},_updateClearAllButtonState:function(){0<
this.totalAppliedFilters?l.add(this.clearAllButton,"esriCTClearAllFilterActive"):l.remove(this.clearAllButton,"esriCTClearAllFilterActive")},_clearAllFilters:function(){if(l.contains(this.clearAllButton,"esriCTClearAllFilterActive")&&this.filterList){var a=h(".applied",this.filterList);k.forEach(a,function(a){(a=h(".header",a))&&0<a.length&&a[0].click()});this._updateClearAllButtonState()}}})});