// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/Legend/Utils":function(){define(["dojo/_base/array","jimu/LayerInfos/LayerInfos"],function(e,f){function g(b,c){return b.isLeaf()?c.layerState[b.id]?c.layerState[b.id].selected:b.getShowLegendOfWebmap():!0}var d=function(b){var c=[],d=f.getInstanceSync().getLayerInfoArray();e.forEach(d,function(a){var d=[];g(a,b)&&(!a.layerObject||"esri.layers.ArcGISDynamicMapServiceLayer"!==a.layerObject.declaredClass&&"esri.layers.ArcGISTiledMapServiceLayer"!==a.layerObject.declaredClass||
e.forEach(a.layerObject.dynamicLayerInfos||a.layerObject.layerInfos,function(h){var c=null;a.traversal(function(a){if(a.subId===h.id)return a.isLeaf()&&!g(a,b)&&d.push(a.originOperLayer.mapService.subId),c=a,!0});c||d.push(h.id)}),a.isMapNotesLayerInfo()?e.forEach(a.getSubLayers(),function(a){g(a,b)&&c.push({layer:a.layerObject,title:"Map Notes - "+a.title})}):c.push({hideLayers:d,layer:a.layerObject,title:a.title}))});return c.reverse()};return{getLayerInfosParam:function(b){return d(b)}}})},"widgets/Legend/_build-generate_module":function(){define(["dojo/text!./Widget.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/Legend/Widget.html":'\x3cdiv\x3e\r\n  \x3c!--div data-dojo-attach-point\x3d"legendDiv"\x3e\x3c/div--\x3e\r\n  \x3cdiv style\x3d"display:none" data-dojo-attach-point\x3d"removedDiv"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n\r\n\r\n',"url:widgets/Legend/css/style.css":".esriLegendServiceLabel {font-size: 14px;}.esriLegendLayer{font-size: 12px;}","*now":function(e){e(['dojo/i18n!*preload*widgets/Legend/nls/Widget*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])},
"*noref":1}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/on ./Utils dijit/_WidgetsInTemplateMixin jimu/BaseWidget jimu/LayerInfos/LayerInfos esri/dijit/Legend".split(" "),function(e,f,g,d,b,c,k,a,l){return e([k,c],{name:"Legend",baseClass:"jimu-widget-legend",legend:null,_jimuLayerInfos:null,startup:function(){this.inherited(arguments)},onOpen:function(){if(!this.config.layerState||this.config.syncWithWebmap)this.config.layerState={};this._jimuLayerInfos=a.getInstanceSync();var b={arrangement:this.config.legend.arrangement,
autoUpdate:this.config.legend.autoUpdate,respectCurrentMapScale:this.config.legend.respectCurrentMapScale,map:this.map,layerInfos:this._getLayerInfosParam()};this.legend=new l(b,g.create("div",{},this.domNode));this.legend.startup();this._bindEvent()},onClose:function(){this.legend.destroy()},_bindEvent:function(){this.config.legend.autoUpdate&&(this.own(d(this._jimuLayerInfos,"layerInfosIsShowInMapChanged",f.hitch(this,"refreshLegend"))),this.own(d(this._jimuLayerInfos,"layerInfosChanged",f.hitch(this,
"refreshLegend"))),this.own(d(this._jimuLayerInfos,"layerInfosRendererChanged",f.hitch(this,"refreshLegend"))))},_getLayerInfosParam:function(){return b.getLayerInfosParam(this.config)},refreshLegend:function(){var a=this._getLayerInfosParam();this.legend.refresh(a)}})});