// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/DistanceAndDirection/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html","dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/DistanceAndDirection/setting/Setting.html":'\x3cdiv style\x3d"width:100%;height:100%;overflow:hidden;" class\x3d"nihilo"\x3e\r\n    \x3cdiv\x3e\r\n      \x3ch3 class\x3d"distance-and-direction-setting-h3"\x3e${nls.feedbackStyleLabel}\x3c/h3\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"feedbackTable" class\x3d"table-feedbacks"\x3e\x3c/div\x3e\r\n      \x3cdiv data-dojo-attach-point\x3d"labelTable" class\x3d"table-labels"\x3e\x3c/div\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/DistanceAndDirection/setting/css/style.css":".distance-and-direction-setting .table-feedbacks{width: 100%; height: 197px; margin-top: 15px;}.distance-and-direction-setting .table-labels{width: 100%; height: 77px; margin-top: 15px;}.distance-and-direction-setting .simple-table-row{height: 40px;}.jimu-simple-table .body-section .table-div {background-image: url(./images/table_under_line.png) !important;}.distance-and-direction-setting {margin-left: 0px;}.distance-and-direction-setting-h3 {color: #596679;}.distance-and-direction-setting-style table {color: #333333; width: 100%; border-collapse: collapse;}.distance-and-direction-setting-style th {background-color: #518dca; padding: 8px; text-align: left; color: #ffffff;}.distance-and-direction-setting-style tr {background-color: #ffffff;}.distance-and-direction-setting-style td {padding: 8px;}.settings-section tr {vertical-align: top;}.distance-and-direction-setting-line-size {width: 70px;}.distance-and-direction-setting-color-picker {width: 70px;}.distance-and-direction-setting-interval-width {border-color: #000; border-style: hidden solid solid solid; border-width: 1px; height: 10px; margin: auto;}.distance-and-direction-setting-style-map {width: 500px; height: 550px; float: left;}",
"*now":function(d){d(['dojo/i18n!*preload*widgets/DistanceAndDirection/setting/nls/Setting*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])},"*noref":1}});
define("dojo/_base/declare dojo/_base/html dojo/_base/lang dojo/_base/array dojo/_base/Color dojo/query jimu/BaseWidgetSetting jimu/dijit/ColorPicker jimu/dijit/SimpleTable dijit/form/NumberSpinner dijit/registry jimu/dijit/Message dijit/_WidgetsInTemplateMixin dijit/ColorPalette".split(" "),function(d,e,b,l,m,f,n,p,g,h,k,q,r){return d([n,r],{baseClass:"distance-and-direction-setting",startup:function(){this.inherited(arguments);var a={fields:[{name:"showTab",title:this.nls.showTabLabel,width:"16%",
type:"checkbox",onChange:b.hitch(this,this._checkBoxChange),"class":"show"},{name:"index",title:"index",type:"text",hidden:!0},{name:"feedbackShape",title:this.nls.feedbackShapeLabel,width:"28%",type:"text"},{name:"lineColor",title:this.nls.lineColorLabel,create:b.hitch(this,this._createColorPicker),setValue:b.hitch(this,this._setColorPicker),getValue:b.hitch(this,this._getColorPicker),width:"28%",type:"extension"},{name:"lineWidth",title:this.nls.lineWidthLabel,create:b.hitch(this,this._createNumberSpinner),
setValue:b.hitch(this,this._setNumberSpinnerValue),getValue:b.hitch(this,this._getNumberSpinnerValue),type:"extension",width:"28%"}],selectable:!0,autoHeight:!1};this.displayFeedbackTable=new g(a);this.displayFeedbackTable.placeAt(this.feedbackTable);e.setStyle(this.displayFeedbackTable.domNode,{height:"100%"});a={fields:[{name:"index",title:"index",type:"text",hidden:!0},{name:"feedbackLabel",title:this.nls.feedbackLabel,width:"44%",type:"text"},{name:"textColor",title:this.nls.textColorLabel,create:b.hitch(this,
this._createColorPicker),setValue:b.hitch(this,this._setColorPicker),getValue:b.hitch(this,this._getColorPicker),width:"28%",type:"extension"},{name:"textSize",title:this.nls.textSizeLabel,create:b.hitch(this,this._createTextNumberSpinner),setValue:b.hitch(this,this._setNumberSpinnerValue),getValue:b.hitch(this,this._getNumberSpinnerValue),type:"extension",width:"28%"}],selectable:!0,autoHeight:!1};this.displayLabelTable=new g(a);this.displayLabelTable.placeAt(this.labelTable);e.setStyle(this.displayLabelTable.domNode,
{height:"100%"});this.setConfig(this.config)},_createColorPicker:function(a){(new p).placeAt(a)},_getColorPicker:function(a){return k.byId(a.childNodes[0].id).getColor()},_setColorPicker:function(a,b){k.byId(a.childNodes[0].id).setColor(new m(b))},_createNumberSpinner:function(a){(new h({value:2,smallDelta:1,constraints:{min:1,max:10,places:0},style:"width:100px"})).placeAt(a)},_createTextNumberSpinner:function(a){(new h({value:12,smallDelta:1,constraints:{min:1,max:36,places:0},style:"width:100px"})).placeAt(a)},
_getNumberSpinnerValue:function(a){return f(".dijitInputInner",a)[0].value},_setNumberSpinnerValue:function(a,b){f(".dijitInputInner",a)[0].value=b},setConfig:function(a){a=[{showTab:a.feedback.lineSymbol.showTab,color:a.feedback.lineSymbol.color,width:a.feedback.lineSymbol.width},{showTab:a.feedback.circleSymbol.showTab,color:a.feedback.circleSymbol.outline.color,width:a.feedback.circleSymbol.outline.width},{showTab:a.feedback.ellipseSymbol.showTab,color:a.feedback.ellipseSymbol.outline.color,width:a.feedback.ellipseSymbol.outline.width},
{showTab:a.feedback.rangeRingSymbol.showTab,color:a.feedback.rangeRingSymbol.color,width:a.feedback.rangeRingSymbol.width},{color:a.feedback.labelSymbol.color,width:a.feedback.labelSymbol.font.size}];this._setFeedbackTable([{shape:"Line"},{shape:"Circle"},{shape:"Ellipse"},{shape:"Rings"}],a);this.displayLabelTable.clear();this.displayLabelTable.addRow({feedbackLabel:this.nls.feedbackLabel,index:"0",textColor:a[4].color,textSize:a[4].width})},_setFeedbackTable:function(a,b){this.displayFeedbackTable.clear();
for(var c=0;c<a.length;c++)this.displayFeedbackTable.addRow({feedbackShape:a[c].shape,index:""+c,showTab:b[c].showTab,lineColor:b[c].color,lineWidth:b[c].width})},getConfig:function(){var a=this.displayFeedbackTable.getData(),b=this.displayLabelTable.getData(),c=0;l.forEach(a,function(a){a.showTab&&(c+=1)});if(0!==c)return this.config.feedback={lineSymbol:{showTab:a[0].showTab,type:"esriSLS",style:"esriSLSSolid",color:a[0].lineColor,width:a[0].lineWidth},circleSymbol:{showTab:a[1].showTab,type:"esriSFS",
style:"esriSFSNull",color:[255,0,0,0],outline:{color:a[1].lineColor,width:a[1].lineWidth,type:"esriSLS",style:"esriSLSSolid"}},ellipseSymbol:{showTab:a[2].showTab,type:"esriSFS",style:"esriSFSNull",color:[255,0,0,0],outline:{color:a[2].lineColor,width:a[2].lineWidth,type:"esriSLS",style:"esriSLSSolid"}},rangeRingSymbol:{showTab:a[3].showTab,type:"esriSLS",style:"esriSLSSolid",color:a[3].lineColor,width:a[3].lineWidth},labelSymbol:{type:"esriTS",color:b[0].textColor,verticalAlignment:"middle",horizontalAlignment:"center",
xoffset:0,yoffset:0,kerning:!0,font:{family:"arial",size:b[0].textSize,style:"normal",weight:"normal",decoration:"none"}}},this.config;new q({message:this.nls.tabErrorMessage});return!1}})});