// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/Deferred jimu/LayerInfos/LayerInfos jimu/DataSourceManager jimu/utils ../../utils".split(" "),function(u,f,v,w,x,r,h){return u(null,{oidFieldType:"esriFieldTypeOID",stringFieldType:"esriFieldTypeString",numberFieldTypes:["esriFieldTypeSmallInteger","esriFieldTypeInteger","esriFieldTypeSingle","esriFieldTypeDouble"],_customColorDefaultNum:5,dateFieldType:"esriFieldTypeDate",constructor:function(a){a&&f.mixin(this,a);this.others=[{text:this.nls.nullText,
label:this.nls.nullText,id:"null",color:"#808080"},{text:this.nls.others,label:this.nls.others,id:"others",color:"#808080"}];this.colors&&(this.customColors=f.clone(this.colors));this.layerInfosObj=w.getInstanceSync();this.dataSourceManager=x.getInstance()},setPreModle:function(a){this.PRE_MODLE=a},setCustomColor:function(a){this.customColors=f.clone(a)},setFeatures:function(a){this.features=a},updateModleComputedWithDefinition:function(a){a.computed.definition&&(this.isDSEqual(a.dataSource,this.PRE_MODLE.dataSource)||
(this._updateSelectFieldOptions(a),this._updateModesByDefinition(a),this._completeLackMode(a)),this._completeLackField(a),this._completedLackConfig(a),a.computed.sortComputed=this._calcuteSortComputed(a),a.computed.showUseLayerSymbology=this._shouldShowUseLayerSymbolDisplay(a),a.computed.showDateOption=this._shouldShowDateOption(a))},updateModleComputedOnlyByConfig:function(a){var b=a.config,c=b.mode,e=b.type,d=this._calcuteSeriesStyleComputed(a);a.computed.seriesStyleComputed=d;d=!0;("feature"===
c||"category"===c)&&b&&"pie"===b.type&&(d=!1);!d&&b.valueFields&&1<b.valueFields.length&&(b.valueFields=b.valueFields.slice(0,1));a.computed.valueFieldsAsMultipleMode=d;"pie"===e?e=!0:(e=!0,"count"===c||"field"===c?e=!1:b.seriesStyle&&(e="layerSymbol"!==b.seriesStyle.type));a.computed.legendDisplay=e},getInitializationModle:function(a){a=this._completeLackColor(a);return f.clone({config:a,computed:{modes:["feature","category","count","field"],categoryFieldOptions:[],labelFieldsOptions:[],valueFields:[],
sortComputed:null,definition:null,showDateOption:"",showUseLayerSymbology:!1,valueFieldsAsMultipleMode:!0,seriesStyleComputed:null,legendDisplay:!0}})},getTempConfigByTempName:function(){if(!this.templates)return null;var a=window.JSON.parse(this.templates).filter(function(a){return a.name===this.templateName}.bind(this))[0];if(!a)return null;var b=null;a.config&&a.config.dijits&&a.config.dijits.length&&a.config.dijits.forEach(function(a){"chart"===a.type&&(b=a.config)});return f.clone(b)},getRandomCustomColor:function(){var a;
a=0;if(this._lastCustomColor){var b=this.customColors.indexOf(this._lastCustomColor);-1<b&&(a=b+1,a>this.customColors.length-1&&(a=0))}return this._lastCustomColor=a=this.customColors[a]},getLayerDefinitionByDataSource:function(a){var b=a.dataSource,c=new v;if(!b)return c.reject("Invaild data source"),c;b.layerId?(a=this.layerInfosObj.getLayerInfoById(b.layerId),this.popupInfo=a.getPopupInfo(),a&&this._getServiceDefinitionByLayerInfo(a).then(function(a){this._addAliasForLayerDefinition(a);c.resolve(a)}.bind(this))):
b.frameWorkDsId&&(a=null,b=(this.appConfig.dataSource&&this.appConfig.dataSource.dataSources)[b.frameWorkDsId],"Features"===b.type?(a=f.clone(b.dataSchema),this._addAliasForLayerDefinition(a),c.resolve(a)):"FeatureStatistics"===b.type&&(a={type:"Table",fields:[]},b=f.clone(b.dataSchema),a.fields=b.fields,b.groupByFields&&b.groupByFields[0]&&(a.groupByFields=f.clone(b.groupByFields)),this._addAliasForLayerDefinition(a),c.resolve(a)));return c},dynamicUpdateModleConfig:function(a){if(a&&a.config){var b=
this._calcuteSortConfig(a);a.config.sortOrder=b;this._dynamicUpdateShowLegend(a)}this._dynamicUpdateSeriesStyle(a)},isDSEqual:function(a,b){if(a&&b)return a=this._cloneAndFormatDS(a),b=this._cloneAndFormatDS(b),h.isEqual(a,b)},_calcuteSeriesStyleComputed:function(a){var b=a.config,c=b.mode,e=b.type,d=b.area,g=b.valueFields||[],f=b.categoryField,m=a.computed;a=m.definition;var n={},p="single",q=!0,k="none",p=[];m.showUseLayerSymbology&&p.push("layerSymbol");"pie"!==e||"category"!==c&&"count"!==c||
h.isDateField(f,a)||p.push("custom");2===p.length&&(k="all");1===p.length&&(k=p[0]);p=1<g.length?"multiply":"single";"line"===e&&"field"===c&&(p="single");"pie"===e&&(q="field"===c);g="";if("category"===c||"count"===c)g=b.categoryField;n.colorSingleMode=q;n.colorDisplayMode=p;n.showOpacity=!!d;n.otherRadio=k;n.categoryField=g;if("custom"===k||"all"===k)b=h.isNumberType(f,a,!0),f=h.isContainCodedValuesField(f,a),n.categoryTypes={isNumberType:b,isCodedValueType:f},n.customColorSelects=this._getCustomColorSelects(g,
a);n.chartType=e;return n},_createSeriesStyle:function(a,b,c){a={name:a,style:{color:this._getRandomColor()}};b&&(a.style.opacity=6);c&&(a.style.color="#68D2E0 #087E92 #47BCF5 #FBE66A #F29157 #C8501D".split(" "));return a},_dynamicUpdateSeriesStyle:function(a){var b=a.config,c=b.mode,e=b.type,d=b.area,g=b.categoryField,l=b.valueFields||[],m=a.computed,n=m.definition;(b=f.clone(b.seriesStyle))||(b={});var p=!1;"line"===e&&d&&(p=!0);d=m.showUseLayerSymbology;"undefined"===typeof b.type&&(b.type="series");
d||"layerSymbol"!==b.type||(b.type="series");"field"===c&&(b.type="series");"feature"===c&&"custom"===b.type&&(b.type="series");g&&h.isDateField(g,n)&&"custom"===b.type&&(b.type="series");var g=b.styles||[],q=[],k=[],d=[],q=g.map(function(a){return a.name}),k=q.filter(function(a){return 0>l.indexOf(a)}),d=l.filter(function(a){return 0>q.indexOf(a)}),r=!1;"column"===e||"bar"===e||"line"===e?"line"===e&&"field"===c?"line~field"===q[0]?(k=[],d=[]):(k=q,d=["line~field"]):"count"===c&&("count~count"===
q[0]?(k=[],d=[]):(k=q,d=["count~count"])):"pie"===e&&"field"!==c&&("pie~not-field"===q[0]?(k=[],d=[]):(r=!0,k=q,d=["pie~not-field"]));g=g.filter(function(a){return 0>k.indexOf(a.name)});c=d.map(function(a){return this._createSeriesStyle(a,p,r)}.bind(this));g=g.concat(c);b.styles=null;b.styles=g;g.forEach(function(a){-1<l.indexOf(a.name)?a.label=h.getFieldAlias(a.name,n,this.popupInfo):a.label=a.name}.bind(this));this._dynamicUpdateSeriesStyleCustomColor(b,a)},_dynamicUpdateSeriesStyleCustomColor:function(a,
b){var c=b.config,e=b.dataSource,d=b.computed.definition,g=c.categoryField,h=this.PRE_MODLE.config,m;"pie"!==c.type||"category"!==c.mode&&"count"!==c.mode?m="remove":a.customColor?"undefined"===typeof this.PRE_MODLE.dataSource?m="keep":this.isDSEqual(e,this.PRE_MODLE.dataSource)&&g===h.categoryField||(m="update"):m="update";c=null;"remove"===m?"undefined"!==typeof a.customColor&&delete a.customColor:"update"===m&&e&&g&&(c=this._getCustomColorCategories(g,d),a.customColor||(a.customColor={}),c&&(a.customColor.categories=
c),a.customColor.others&&a.customColor.others.length||(a.customColor.others=f.clone(this.others)));b.config&&(b.config.seriesStyle=a)},_dynamicUpdateShowLegend:function(a){a=a.config;var b=a.mode,c;"pie"!==a.type&&("count"===b||"field"===b?c=!0:a.seriesStyle&&"layerSymbol"===a.seriesStyle.type&&(c=!0),c&&(a.showLegend=!1))},_getCustomColorSelects:function(a,b){var c=this._getCategoriesByFeatures(a);if(c&&c.length){var c=c.filter(function(a){return!!a||0===a}),e=[];return e=h.isContainCodedValuesField(a,
b)?c.map(function(c){var d=c;c=this._getDominDisplayValue(a,c,b);return{label:c,value:d}}.bind(this)):c.map(function(a){return{label:a,value:a}})}},_getCustomColorCategories:function(a,b){var c=this._getCategoriesByFeatures(a);if(c&&c.length){c=c.filter(function(a){return!!a||0===a});c.length>this._customColorDefaultNum&&(c=c.slice(0,this._customColorDefaultNum));var e=[];return e=h.isContainCodedValuesField(a,b)?c.map(function(c){var d=c;c=this._getDominDisplayValue(a,c,b);return{id:d,text:c,label:c,
color:this.getRandomCustomColor()}}.bind(this)):c.map(function(a){return{id:a,text:a,label:a,color:this.getRandomCustomColor()}}.bind(this))}},_getCategoriesByFeatures:function(a){var b=[];if(!this.features||!this.features.length)return b;this.features.forEach(f.hitch(this,function(c){c=c.attributes[a];0>b.indexOf(c)&&b.push(c)}));return this._sortOrderCategories(b)},_calcuteSortConfig:function(a){var b={},c=this.PRE_MODLE.config,e=a.config,d=e.sortOrder;a=this._getSortFields(a);h.isEqual(e.mode,
c.mode)||"undefined"===typeof c.mode?b=f.clone(d):(b.isAsc=!0,"feature"===e.mode?a&&a[0]&&(b.field=a[0].value):b.isLabelAxis=!0);return b},_getSortFields:function(a){if(a){var b=a.computed.definition,c=a.config,e=c.mode;if(b&&c&&("feature"===e||c.valueFields&&c.valueFields[0])){var d=[];"feature"===e?(d=f.clone(b.fields),d=h.getNotGeometryFields(d)):c.valueFields&&(d=h.getFieldInfosByFieldName(c.valueFields,a.computed.definition));return d.map(function(a){return{value:a.name,label:a.alias||a.name}})}}},
_getInitSortOrderConfig:function(a){var b=a.config,c=null;if(!b&&!b.mode)return c;var e;(a=this._getSortFields(a))&&a[0]&&(e=a[0].value);"feature"===b.mode?e&&(c={field:e,isAsc:!0}):c={isLabelAxis:!0,isAsc:!0};return c},_calcuteSortComputed:function(a){var b={},c=a.config,e=c.sortOrder,c=c.mode,d=this.PRE_MODLE.config.mode;b.mode=c;a=this._getSortFields(a);b.fieldOption=a;!h.isEqual(c,d)&&d?b.sortArrowPosition="feature"===c?"down":"top":b.sortArrowPosition="feature"===c?"down":e.isLabelAxis?"top":
"mid";return b},_addAliasForLayerDefinition:function(a){a&&a.fields&&0<a.fields.length&&a.fields.forEach(f.hitch(this,function(a){var b=h.getFieldAliasByFieldInfo(a,this.popupInfo);b&&(a.alias=b)}))},_getServiceDefinitionByLayerInfo:function(a){return a.getServiceDefinition().then(f.hitch(this,function(b){return b?b:a.getLayerObject().then(f.hitch(this,function(a){return a?r.getFeatureLayerDefinition(a):null}))}))},_cloneAndFormatDS:function(a){a=f.clone(a);var b={};a.name&&(b.name=a.name);a.dataSourceType&&
(b.dataSourceType=a.dataSourceType);a.layerId&&(b.layerId=a.layerId);a.frameWorkDsId&&(b.frameWorkDsId=a.frameWorkDsId);a=null;return b},_getFeatureLayer:function(a){var b=null;this.map&&"undefined"!==typeof a&&(b=this.map.getLayer(a));return b},_completeLackMode:function(a){var b=a.computed;a=a.config;!a.mode&&b.modes&&b.modes.length&&(a.mode=b.modes[0])},_completeLackField:function(a){var b=a.computed;a=a.config;var c=a.mode;"feature"===c?!a.labelField&&b.labelFieldsOptions.length&&(a.labelField=
b.labelFieldsOptions[0].value):"category"!==c&&"count"!==c||a.categoryField||!b.categoryFieldOptions.length||(a.categoryField=b.categoryFieldOptions[0].value)},_completedLackConfig:function(a){var b=a.computed,c=a.config,e=c.mode,d=["sortOrder","seriesStyle"];switch(e){case "feature":d.push("valueFields");break;case "category":case "field":d=d.concat(["operation","nullValue","valueFields"])}"category"!==e&&"count"!==e||!h.isDateField(c.categoryField,b.definition)||d.push("dateConfig");d.forEach(function(b){switch(b){case "valueFields":c&&
!c.valueFields&&(c.valueFields=[]);break;case "sortOrder":c&&!c.sortOrder&&(c.sortOrder=this._getInitSortOrderConfig(a));break;case "seriesStyle":c&&!c.seriesStyle&&(c.seriesStyle={styles:[]});break;case "operation":c&&!c.operation&&(c.operation="sum");break;case "nullValue":c&&"undefined"===typeof c.nullValue&&(c.nullValue=!0);break;case "dateConfig":c&&!c.dateConfig&&(b={isNeedFilled:!0,minPeriod:"automatic"},"pie"===c.type&&(b.isNeedFilled=!1),c.dateConfig=b)}}.bind(this))},_completeLackColor:function(a){if(!a||
!a.type)return!1;var b=this._getDefaultColorOfTheme(),c=b.textColor,b=b.bgColor;a.backgroundColor||(a.backgroundColor=b);b=[];switch(a.type){case "column":case "bar":case "line":b=b.concat(["legendTextColor","horizontalAxisTextColor","verticalAxisTextColor"]);break;case "pie":b=b.concat(["legendTextColor","dataLabelColor"])}b.forEach(function(b){"undefined"!==typeof a[b]&&a[b]||(a[b]=c)});return a},_updateModesByDefinition:function(a){var b=!1,c=["feature","category","count","field"],e=a.computed.definition,
d=a.dataSource;d.frameWorkDsId&&(d=(this.appConfig.dataSource&&this.appConfig.dataSource.dataSources)[d.frameWorkDsId],"FeatureStatistics"===d.type&&(b=!0,c=0<(f.clone(d.dataSchema).groupByFields||[]).length?this._hasNumberFields(e)?["category","count"]:["count"]:["field"]));b||this._hasNumberFields(e)||(c=["count"]);a.computed.modes=c},_updateSelectFieldOptions:function(a){var b=a.computed.definition;a=a.computed;var c=f.clone(b.fields);c.forEach(function(a){a.checked=!1});var e=[this.stringFieldType,
this.dateFieldType,this.oidFieldType],e=e.concat(f.clone(this.numberFieldTypes)),d=c.filter(f.hitch(this,function(a){return 0<=e.indexOf(a.type)}));a.categoryFieldOptions=d.map(f.hitch(this,function(a){return{label:a.alias||a.name,value:a.name}}));b.groupByFields&&b.groupByFields[0]&&(a.categoryFieldOptions=a.categoryFieldOptions.filter(function(a){return a.value===b.groupByFields[0]}));var g=[this.stringFieldType,this.oidFieldType,this.dateFieldType].concat(f.clone(this.numberFieldTypes)),d=c.filter(f.hitch(this,
function(a){return 0<=g.indexOf(a.type)}));a.labelFieldsOptions=d.map(f.hitch(this,function(a){return{label:a.alias||a.name,value:a.name}}));a.valueFields=c.filter(f.hitch(this,function(a){return 0<=this.numberFieldTypes.indexOf(a.type)}));if(b.groupByFields&&b.groupByFields[0]){var h=a.categoryFieldOptions.map(function(a){return a.value});a.valueFields=a.valueFields.filter(function(a){return 0>h.indexOf(a.name)})}},_shouldShowUseLayerSymbolDisplay:function(a){var b=a.computed.definition,c=!1,e=a.config.mode;
if("line"===a.config.type||"field"===e)return c;var d,f=null,l=null;a.dataSource&&(l=a.dataSource,l.layerId?d=l.layerId:l.frameWorkDsId&&(l=this.dataSourceManager.parseDataSourceId(l.frameWorkDsId))&&"undefined"!==l.layerId&&(d=l.layerId));d&&(f=this._getFeatureLayer(d));if(!d)return c;if("feature"===e)c=!0;else if("category"===e||"count"===e){a=a.config.categoryField;if(!f)return c;f.renderer&&(f=f.renderer,"esri.renderer.ClassBreaksRenderer"===f.declaredClass||"esri.renderer.UniqueValueRenderer"===
f.declaredClass)&&(f.attributeField!==a||h.isDateField(a,b)||(c=!0))}return c},_sortOrderCategories:function(a){Array.isArray(a)&&a.sort(function(a,c){"string"===typeof s&&(a=a.toLowerCase());"string"===typeof t&&(c=c.toLowerCase());r.isNumberOrNumberString(a)&&(a=Number(a));r.isNumberOrNumberString(c)&&(c=Number(c));return a<c?-1:a>c?1:0}.bind(this));return a},_getDominDisplayValue:function(a,b,c){var e=b;(a=h.getFieldInfo(a,c))&&a.domain&&(a=a.domain.codedValues)&&0<a.length&&a.some(function(a){return a.code===
b?(e=a.name,!0):!1});return e},_getRandomColor:function(){var a;a=0;if(this._lastColor){var b=this.colors.indexOf(this._lastColor);-1<b&&(a=b+1,a>this.colors.length-1&&(a=0))}return this._lastColor=a=this.colors[a]},_hasNumberFields:function(a){var b=!1;(a=a.fields)&&0<a.length&&(b=a.some(f.hitch(this,function(a){return 0<=this.numberFieldTypes.indexOf(a.type)})));return b},_shouldShowDateOption:function(a){var b=h.isDateField(a.config.categoryField,a.computed.definition);a=a.config.mode;return("category"===
a||"count"===a)&&b},_getDefaultColorOfTheme:function(){var a={bgColor:"#fff",textColor:"#000"};if(!this.appConfig)return a;"DashboardTheme"!==this.appConfig.theme.name||"default"!==this.appConfig.theme.styles[0]&&"style3"!==this.appConfig.theme.styles[0]?"DartTheme"===this.appConfig.theme.name&&(a.bgColor="#4c4c4c",a.textColor="#fff"):(a.bgColor="#222222",a.textColor="#fff");return a}})});