// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define(["dojo/_base/lang","moment/moment","./_chartHelpUtils","jimu/utils"],function(p,n,t,q){window.makeTwix&&window.makeTwix(n);return{getClietStatisticsData:function(a){var b=a.mode;if("feature"===b)return this.getFeatureModeStatisticsData(a);if("category"===b)return this.getCategoryModeStatisticsData(a);if("count"===b)return this.getCountModeStatisticsData(a);if("field"===b)return this.getFieldModeStatisticsData(a)},sortClientStatisticsData:function(a,b){return this.sortStatisticsData(a,b.mode,
b.sortOrder,b.clusterField,b.valueFields)},getDataForMaxLabels:function(a,b){return"number"===typeof b&&0<=b&&b<a.length?a.slice(0,b):a},getFeatureModeStatisticsData:function(a){var b=a.features,c=a.clusterField,d=a.valueFields;a=a.showNullLabelData||!0;var f=this._separateFeaturesWhetherFieldValueNull(c,b),b=f.notNullLabelFeatures,f=f.nullLabelFeatures,b=a?b.concat(f):b;a=[];return a=b.map(function(a){var b=a.attributes,e=b[c],e=this._convertingNullOrUndefinedAsPlaceholders(e);a={label:e,values:[],
features:[a]};a.values=d.map(function(a){return b[a]});return a}.bind(this))},getCategoryModeStatisticsData:function(a){function b(a){var b=[],e=null,h;for(h in a){(e=a[h])&&"number"===e.type&&(h=Number(h));g&&"_NULL\x26UNDEFINED_"!==h&&(h=Number(h));var l=c||d;e.fieldsValues=f.map(function(a){var b=a;if(l){var c=k;"average"===c&&(c="avg");b=this._mosaicFieldNameWithOperatorAndUpper(a,c)}var d=e.dataFeatures.map(p.hitch(this,function(d){var e=d.attributes[b];"undefined"===typeof e&&l&&(b=this._mosaicFieldNameWithOperatorAndLower(a,
c),e=d.attributes[b]);return e})),h;if(0!==d.length){h=0;"max"===k?h=-Infinity:"min"===k&&(h=Infinity);var d=m?d.map(function(a){this._isNumber(a)||(a=0);return a}.bind(this)):d.filter(function(a){return this._isNumber(a)}.bind(this)),f=0;d.forEach(p.hitch(this,function(a){f++;"average"===k||"sum"===k?h+=a:"max"===k?h=Math.max(h,a):"min"===k&&(h=Math.min(h,a))}));0<f?"average"===k&&(h/=f):h=null}else h=null;return{field:a,value:h}}.bind(this));e.valueFields=e.fieldsValues.map(function(a){return a.value});
b.push({label:h,values:e.valueFields,features:e.dataFeatures,unit:e.unit})}return b}var c=a.forExtraSTD,d=a.hasStatisticsed,f=a.valueFields,k=a.operation,g=a.dateConfig,e=a.showNullLabelData||!0,m=a.nullValue,l=[],l=this.getCluseringObj(a.clusterField,a.features,g);a=l.nullLabelClusteringObj;l=b.call(this,l.notNullLabelClusteringObj);a=b.call(this,a);return l=e?l.concat(a):l},getCountModeStatisticsData:function(a){function b(a){var b=[],c=null,d;for(d in a)(c=a[d])&&"number"===c.type&&(d=Number(d)),
k&&"_NULL\x26UNDEFINED_"!==d&&(d=Number(d)),b.push({label:d,values:[c.count],features:c.dataFeatures,unit:c.unit});return b}var c=a.hasStatisticsed,d=a.features,f=a.clusterField,k=a.dateConfig,g=a.showNullLabelData||!0,e=[];if((a.forExtraSTD||c)&&!k){c=this._separateFeaturesWhetherFieldValueNull(f,d);a=c.notNullLabelFeatures;var c=c.nullLabelFeatures,d=g?a.concat(c):a,m=["STAT_COUNT"];return e=d.map(function(a){var b=a.attributes,c=b[f],c=this._convertingNullOrUndefinedAsPlaceholders(c);a={label:c,
values:[],features:[a]};a.values=m.map(function(a){var c=b[a];"undefined"===typeof c&&(a=q.lowerCaseString(a),c=b[a]);return c});return a}.bind(this))}c=this.getCluseringObj(f,d,k);a=c.nullLabelClusteringObj;c=b.call(this,c.notNullLabelClusteringObj);a=b.call(this,a);return e=g?c.concat(a):c},_convertingNullOrUndefinedAsPlaceholders:function(a){return null===a||void 0===a?"_NULL\x26UNDEFINED_":a},getFieldModeStatisticsData:function(a){var b=a.forExtraSTD,c=a.hasStatisticsed,d=a.valueFields,f=a.operation,
k=a.nullValue,g=a.features.map(p.hitch(this,function(a){return a.attributes})),e={},m=b||c;d.forEach(p.hitch(this,function(a){var b=a;if(m){var c=f;"average"===c&&(c="avg");b=this._mosaicFieldNameWithOperatorAndUpper(a,c)}e[a]=0;"max"===f?e[a]=-Infinity:"min"===f&&(e[a]=Infinity);var d=g.map(function(d){var e=d[b];"undefined"===typeof e&&m&&(b=this._mosaicFieldNameWithOperatorAndLower(a,c),e=d[b]);return e}.bind(this)),h=0,d=k?d.map(function(a){this._isNumber(a)||(a=0);return a}.bind(this)):d.filter(function(a){return this._isNumber(a)}.bind(this));
d.forEach(p.hitch(this,function(b){h++;e.hasOwnProperty(a)?"average"===f||"sum"===f?e[a]+=b:"max"===f?e[a]=Math.max(e[a],b):"min"===f&&(e[a]=Math.min(e[a],b)):e[a]=b}));0<h?"average"===f&&(e[a]/=h):e[a]=null}));a=[];for(var l in e)e.hasOwnProperty(l)&&a.push({label:l,values:[e[l]]});return a},sortStatisticsData:function(a,b,c,d,f){function k(a,b,c){var e;"category"===b?c.isLabelAxis?c.isLabelAxis&&(e=a.label):c.field||1!==a.values.length?(c=f.indexOf(c.field),e=a.values[c]):e=a.values[0]:"count"===
b?(e=a.label,e=c.isLabelAxis?e:a.values[0]):"field"===b?e=c.isLabelAxis?a.label:a.values[0]:"feature"===b&&a&&a.features&&a.features[0]&&(a=a.features[0].attributes)&&(e=c.isLabelAxis?a[d]:a[c.field]);return e}if(!c)return a;var g=c.isAsc;if(!Array.isArray(a))return a;a.sort(function(a,d){a=k(a,b,c);d=k(d,b,c);"_NULL\x26UNDEFINED_"===a&&(a=Infinity);"_NULL\x26UNDEFINED_"===d&&(d=Infinity);q.isNumberOrNumberString(a)&&(a=Number(a));q.isNumberOrNumberString(d)&&(d=Number(d));var e=a>d?g:!g;Infinity===
a?e=g:Infinity===d&&(e=!g);var f=0;a!==d&&(f=e?1:-1);return f}.bind(this));return a},_isNumber:function(a){return"[object number]"===Object.prototype.toString.call(a).toLowerCase()},_getDateUnit:function(a,b){var c=b;"automatic"===b&&(b=n(a[0]).local(),a=n(a[1]).local(),a=Math.round(a.diff(b,"minute",!0)),0<=a&&1>=a?c="second":1<a&&60>=a?c="minute":60<a&&1440>=a?c="hour":1440<a&&43200>=a?c="day":43200<a&&518400>=a?c="month":518400<a&&(c="year"));return c},_getTimeRange:function(a,b){var c=a.map(p.hitch(this,
function(a){return a.attributes[b]})),c=c.filter(function(a){return!!a});a=Math.min.apply(Math,c);c=Math.max.apply(Math,c);return[a,c]},_getTimeTwixs:function(a,b,c){if(0>"year month day hour minute second automatic".split(" ").indexOf(c))return console.log("Invaild data formatter: "+c),!1;a=this._getTimeRange(a,b);if(a[0]===a[1])return!1;c=this._getDateUnit(a,c);b=this.getStartTimeByUnit(a[0],c);b=n(b).local();a=n(a[1]).local();a=b.twix(a).split(1,c);b={startValue:a[a.length-1].end().valueOf(),endValue:Infinity};
a.push(b);return{twixs:a,dateUnit:c}},getCluseringObj:function(a,b,c){var d={},f={};c?(a=this.getClusteringObjForDateType(a,b,c),d=a.notNullLabelClusteringObj,f=a.nullLabelClusteringObj):(d=this._separateFeaturesWhetherFieldValueNull(a,b),b=d.nullLabelFeatures,d=this.getClusteringObjByField(d.notNullLabelFeatures,a),f=this.getClusteringObjByField(b,a));return{notNullLabelClusteringObj:d,nullLabelClusteringObj:f}},getClusteringObjByField:function(a,b){var c={};a.forEach(p.hitch(this,function(a){var d=
a.attributes[b],k=typeof d,d=this._convertingNullOrUndefinedAsPlaceholders(d),g=null;c.hasOwnProperty(d)?(g=c[d],g.dataFeatures.push(a),g.count++):(g={count:1,dataFeatures:[a],type:k},c[d]=g)}));return c},_removeNaNDataItem:function(a){return a.filter(function(a){var b=!1;a=a.category;"number"===typeof a&&(b=isNaN(a));return!b})},_separateFeaturesWhetherFieldValueNull:function(a,b){var c=[],d=[];Array.isArray(b)&&(d=b.filter(function(b){var d=b.attributes[a];if(null===d||void 0===d)c.push(b);else return!0}));
return{nullLabelFeatures:c,notNullLabelFeatures:d}},getStartTimeByUnit:function(a,b){return n(a).startOf(b).utc().valueOf()},_mosaicFieldNameWithOperatorAndUpper:function(a,b){return q.upperCaseString(a+"_"+b)},_mosaicFieldNameWithOperatorAndLower:function(a,b){return q.lowerCaseString(a+"_"+b)},getClusteringObjForDateType:function(a,b,c){function d(a,b,c){a[b]?(a=a[b],a.count+=c.count,a.dataFeatures=a.dataFeatures.concat(c.dataFeatures)):a[b]=c}function f(a,b,c,d){b=Number(b);d=this.getStartTimeByUnit(b,
d);a[d]?(a=a[d],a.count+=c.count,a.dataFeatures=a.dataFeatures.concat(c.dataFeatures)):(c.originTime=b,a[d]=c)}function k(a,b,c){c[a[0].attributes[b]]={count:1,dataFeatures:a};return c}var g=this._separateFeaturesWhetherFieldValueNull(a,b),e=g.notNullLabelFeatures;b={};b=this.getClusteringObjByField(g.nullLabelFeatures,a);g={};if(1===e.length)g=k.call(this,e,a,g,c);else if(0!==e.length){var m=this._getTimeTwixs(e,a,c.minPeriod);if(m){var l={},h=m.dateUnit;m.twixs.forEach(function(b){var k="undefined"!==
typeof b.startValue?b.startValue:b.start().valueOf(),f="undefined"!==typeof b.endValue?b.endValue:b.end().valueOf(),g={unit:h,count:0,dataFeatures:[]};e.forEach(p.hitch(this,function(b){var c=b.attributes[a];c>=k&&c<f&&(g.dataFeatures.push(b),g.count++)}));c.isNeedFilled?d.call(this,l,k,g):0<g.count&&d.call(this,l,k,g)}.bind(this));var m={},r,n;for(r in l)l.hasOwnProperty(r)&&(n=l[r],f.call(this,m,r,n,h));for(r in m)if(m.hasOwnProperty(r)){n=m[r];var q=n.originTime;delete n.originTime;g[q]=n}}else g=
k.call(this,e,a,g,c)}return{notNullLabelClusteringObj:g,nullLabelClusteringObj:b}},_mapOptions:function(a,b){"feature"===b?(b=a.labelField,delete a.labelField,a.clusterField=b,a.showNullLabelData=!0):"category"===b?(b=a.categoryField,delete a.categoryField,a.clusterField=b,a.showNullLabelData=!0):"count"===b?(b=a.categoryField,delete a.categoryField,a.clusterField=b):"field"===b&&(a.showNullLabelData=!0);return a},_mapDataItemForStatisticsChart:function(a,b){var c,d,f;return a.map(function(a){c=a.label;
delete a.label;d=a.values;delete a.values;f=a.features;delete a.features;"feature"===b?(a.category=c,a.valueFields=d,a.dataFeatures=f):"category"===b?(a.category=c,a.valueFields=d,a.dataFeatures=f):"count"===b?(a.fieldValue=c,a.count=d[0],a.dataFeatures=f):"field"===b&&(a.label=c,a.value=d[0]);return a})},getFeatureModeStatisticsInfo:function(a){var b=new t({featureLayer:a.layerDefinition,popupFieldInfosObj:a.popupFieldInfosObj});a=this._mapOptions(a,"feature");var c=a.clusterField,d=this.getFeatureModeStatisticsData(a),
d=this.sortStatisticsData(d,"feature",a.sortOrder,c),d=this.getDataForMaxLabels(d,a.maxLabels),d=b.getBestLabelDisplay(d,c,"feature"),d=b.keepStatisticsDataBestDecimalPlace(a,d,"feature");return this._mapDataItemForStatisticsChart(d,"feature")},getCategoryModeStatisticsInfo:function(a){var b=new t({featureLayer:a.layerDefinition,popupFieldInfosObj:a.popupFieldInfosObj});a=this._mapOptions(a,"category");var c=a.clusterField,d=this.getCategoryModeStatisticsData(a),d=this.sortStatisticsData(d,"category",
a.sortOrder,null,a.valueFields),d=this._removeNaNDataItem(d),d=this.getDataForMaxLabels(d,a.maxLabels),d=b.getBestLabelDisplay(d,c,"category"),d=b.keepStatisticsDataBestDecimalPlace(a,d,"category");return this._mapDataItemForStatisticsChart(d,"category")},getCountModeStatisticsInfo:function(a){var b=new t({featureLayer:a.layerDefinition,popupFieldInfosObj:a.popupFieldInfosObj});a=this._mapOptions(a,"count");var c=a.clusterField,d=this.getCountModeStatisticsData(a),d=this.sortStatisticsData(d,"count",
a.sortOrder),d=this.getDataForMaxLabels(d,a.maxLabels),d=b.getBestLabelDisplay(d,c,"count");return this._mapDataItemForStatisticsChart(d,"count")},getFieldModeStatisticsInfo:function(a){var b=new t({featureLayer:a.layerDefinition,popupFieldInfosObj:a.popupFieldInfosObj});a=this._mapOptions(a,"category");var c=this.getFieldModeStatisticsData(a),c=this.sortStatisticsData(c,"field",a.sortOrder),c=this.getDataForMaxLabels(c,a.maxLabels),c=b.getBestLabelDisplay(c,null,"field"),c=b.keepStatisticsDataBestDecimalPlace(a,
c,"field");return this._mapDataItemForStatisticsChart(c,"field")}}});