// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("exports dojo/_base/lang dojo/_base/array dojo/_base/html dojo/has dojo/Deferred jimu/utils esri/lang esri/tasks/QueryTask esri/tasks/query".split(" "),function(e,q,n,v,u,r,p,x,y,z){function w(b){var d=q.clone(b.attributes);(b=b.geometry)&&"point"===b.type&&("x"in d?d._x=b.x:d.x=b.x,"y"in d?d._y=b.y:d.y=b.y);return d}e.exportCSV=function(b,d,c){return e._createCSVStr(d,c).then(function(a){return e._download(b+".csv",a)})};e.exportCSVFromFeatureLayer=function(b,d,c){c=c||{};return e._getExportData(d,
{datas:c.datas,objectIds:c.objectIds,fromClient:c.fromClient,withGeometry:c.withGeometry,outFields:c.outFields,filterExpression:c.filterExpression,outSpatialReference:c.outSpatialReference}).then(function(a){return e._formattedData(d,a,{formatNumber:c.formatNumber,formatDate:c.formatDate,formatCodedValue:c.formatCodedValue,popupInfo:c.popupInfo}).then(function(a){return e.exportCSV(b,a.datas,a.columns)})})};e.exportCSVByAttributes=function(b,d,c,a){a=q.mixin({},a);a.datas=c;return e.exportCSVFromFeatureLayer(b,
d,a)};e.exportCSVByGraphics=function(b,d,c,a){c=n.map(c,function(a){return a.attributes});return e.exportCSVByAttributes(b,d,c,a)};e._createCSVStr=function(b,d){var c=new r,a="",e=0,f=0,g="",h="";try{d=n.map(d,function(a){return"string"===typeof a?{name:a}:a});n.forEach(d,function(b){b=b.alias||b.name;-1<b.toString().indexOf(",")&&(b='"'+b+'"');a=a+g+b;g=","});for(var a=a+"\r\n",e=b.length,f=d.length,l=0;l<e;l++){for(var g="",k=0;k<f;k++)(h=b[l][d[k].name])||"number"===typeof h||(h=""),h&&/[",\r\n]/g.test(h)&&
(h='"'+h.replace(/(")/g,'""')+'"'),a=a+g+h,g=",";a+="\r\n"}c.resolve(a)}catch(t){console.error(t),c.resolve("")}return c};e._isIE11=function(){return 11===p.has("ie")};e._isEdge=function(){return p.has("edge")};e._getDownloadUrl=function(b){return window.Blob&&window.URL&&window.URL.createObjectURL?(b=new Blob(["\ufeff"+b],{type:"text/csv"}),URL.createObjectURL(b)):"data:attachment/csv;charset\x3dutf-8,\ufeff"+encodeURIComponent(b)};e._download=function(b,d){var c=new r;try{if(u("ie")&&10>u("ie")){var a=
window.top.open("about:blank","_blank");a.document.write("sep\x3d,\r\n"+d);a.document.close();a.document.execCommand("SaveAs",!0,b);a.close()}else if(10===u("ie")||e._isIE11()||e._isEdge()){var m=new Blob(["\ufeff"+d],{type:"text/csv"});navigator.msSaveBlob(m,b)}else{var f=v.create("a",{href:e._getDownloadUrl(d),target:"_blank",download:b},document.body);if(u("safari")){var g=document.createEvent("MouseEvents");g.initEvent("click",!0,!0);f.dispatchEvent(g)}else f.click();v.destroy(f)}c.resolve()}catch(h){c.reject(h)}return c};
e._getExportData=function(b,d){var c=new r,a=null,m=[],f=d.datas,g=d.withGeometry,a=d.outFields;a&&a.length||(a=b.fields);a=q.clone(a);if(g&&!(f&&0<f.length)){var m=q.clone(a),h="",h=-1!==a.indexOf("x")?"_x":"x";a.push({name:h,alias:h,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"});h=-1!==a.indexOf("y")?"_y":"y";a.push({name:h,alias:h,format:{digitSeparator:!1,places:6},show:!0,type:"esriFieldTypeDouble"})}f&&0<f.length?c.resolve({data:f||[],outFields:a}):d.fromClient?(f=
n.map(b.graphics,function(a){return g?w(a):q.clone(a)}),c.resolve({data:f||[],outFields:a})):e._getExportDataFromServer(b,m,d).then(function(b){c.resolve({data:b||[],outFields:a})});return c};e._getExportDataFromServer=function(b,d,c){var a=new r;if("esri.layers.FeatureLayer"!==b.declaredClass)return a.resolve([]),a;var e=new y(b.url),f=new z;f.where=c.filterExpression||b.getDefinitionExpression&&b.getDefinitionExpression()||"1\x3d1";0<d.length?(b=n.map(d,function(a){return a.name}),f.outFields=b):
f.outFields=["*"];f.objectIds=c.objectIds;f.returnGeometry=c.withGeometry;f.outSR=c.spatialReference;e.execute(f,function(b){b=n.map(b.features,function(a){return w(a)});a.resolve(b)},function(b){console.error(b);a.resolve([])});return a};e._formattedData=function(b,d,c){var a=new r,m=[],f=d.data;d=d.outFields;for(var g=0,h=f.length;g<h;g++){for(var l={},k=0;k<d.length;k++){var t=d[k];l[t.name]=e._getExportValue(f[g][t.name],t,b.objectIdField,b.typeIdField,f[g][b.typeIdField],b.types,c)}m.push(l)}b=
n.map(d,function(a){return{alias:a.alias,name:a.name}});a.resolve({datas:m,columns:b});return a};e._getExportValue=function(b,d,c,a,e,f,g){function h(a){if(l&&x.isDefined(l.fieldInfos))for(var b=0,d=l.fieldInfos.length;b<d;b++){var c=l.fieldInfos[b];if(c.fieldName===a)return c.format}return null}var l=g.popupInfo,k=!!d.domain&&g.formatCodedValue;g="esriFieldTypeDate"===d.type&&g.formatDate;var m=c&&d.name===c;a=a&&d.name===a;return g?p.fieldFormatter.getFormattedDate(b,h(d.name)):a?p.fieldFormatter.getTypeName(b,
f):k?p.fieldFormatter.getCodedValue(d.domain,b):k||g||m||a?b:(k=null,c&&f&&0<f.length&&(c=(c=n.filter(f,function(a){return a.id===e}))&&c[0])&&c.domains&&c.domains[d.name]&&c.domains[d.name].codedValues&&(k=p.fieldFormatter.getCodedValue(c.domains[d.name],b)),null!==k?k:b)}});