// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/promise/all dojo/Deferred jimu/utils jimu/ServiceDefinitionManager esri/tasks/query esri/tasks/QueryTask esri/tasks/FeatureSet".split(" "),function(m,d,h,n,k,l,p,f,g,q){var e=m(null,{queryType:0,nextPageIndex:1,pageSizeOption:null,layerDefinition:null,layerDefinitionDef:null,type1CountDef:null,type2ObjectIdsDef:null,type3QueryDef:null,sdf:null,url:null,query:null,pageSize:1E3,constructor:function(a){this.sdf=p.getInstance();this.url=
a.url;this.query=a.query;this.pageSizeOption=a.pageSize;this.query.outFields&&0!==this.query.outFields.length||(this.query.outFields=["*"]);this.pageSize=0<a.pageSize?a.pageSize:1E3;this.getFeatureCount()},getFeatureCount:function(){return this._getQueryType().then(d.hitch(this,function(a){return 1===a?this._getCountForQueryType1():2===a?this._getCountForQueryType2():this._getCountForQueryType3()}))},getPageCount:function(){return this.getFeatureCount().then(d.hitch(this,function(a){return 0===a?
0:3===this.queryType?1:Math.ceil(a/this.pageSize)}))},getAllFeatures:function(){return this.getPageCount().then(d.hitch(this,function(a){if(0<a){for(var b=[],c=1;c<=a;c++)b.push(this.queryByPage(c));return n(b).then(d.hitch(this,function(a){for(var b=[],c=0;c<a.length;c++)a[c].features&&0<a[c].features.length&&(b=b.concat(a[c].features));a=a[0];a.features=b;return a}))}return this._getEmptyFeatureSet()}))},_getEmptyFeatureSet:function(){var a=new q;a.features=[];a.geometryType=this.layerDefinition.geometryType;
a.fields=[];var b=d.clone(this.layerDefinition.fields);0<=this.query.outFields.indexOf("*")?a.fields=b:a.fields=h.filter(b,d.hitch(this,function(a){return 0<=this.query.outFields.indexOf(a.name)}));return a},getCurrentPageIndex:function(){return this.nextPageIndex},queryNextPage:function(){var a=this.nextPageIndex;this.nextPageIndex++;return this.queryByPage(a)},queryByPage:function(a){var b=null,c=this._getEmptyFeatureSet();0>=a?(b=new k,b.resolve(c)):b=this.getPageCount().then(d.hitch(this,function(b){return a>
b?c:1===this.queryType?this._queryPageForType1(a):2===this.queryType?this._queryPageForType2(a):this._queryPageForType3(a)}));return b},_getQueryType:function(){var a=new k;if(0<this.queryType)a.resolve(this.queryType);else return this._getLayerDefinition().then(d.hitch(this,function(a){return this.queryType=e.getQueryType(a)}));return a},_getDefStatus:function(a){return a?a.isFulfilled()?a.isResolved()?2:-1:1:0},_getLayerDefinition:function(){0>=this._getDefStatus(this.layerDefinitionDef)&&(this.layerDefinitionDef=
this.sdf.getServiceDefinition(this.url).then(d.hitch(this,function(a){this.layerDefinition=a;var b=a.maxRecordCount;0<b&&(!(0<this.pageSizeOption)||this.pageSize>a.maxRecordCount)&&(this.pageSize=b);return this.layerDefinition})));return this.layerDefinitionDef},_getCountForQueryType1:function(){0>=this._getDefStatus(this.type1CountDef)&&(this.type1CountDef=this._queryCount());return this.type1CountDef},_getCountForQueryType2:function(){return this._getObjectIdsForQueryType2().then(d.hitch(this,function(a){return a.length}))},
_getObjectIdsForQueryType2:function(){0>=this._getDefStatus(this.type2ObjectIdsDef)&&(this.type2ObjectIdsDef=this._queryIds());return this.type2ObjectIdsDef},_getCountForQueryType3:function(){return this._doQueryForQueryType3().then(d.hitch(this,function(a){return(a.features||[]).length}))},_doQueryForQueryType3:function(){0>=this._getDefStatus(this.type3QueryDef)&&(this.type3QueryDef=this._query());return this.type3QueryDef},_queryPageForType1:function(a){return this._queryWithPaginationAndOrder((a-
1)*this.pageSize)},_queryPageForType2:function(a){return this._getObjectIdsForQueryType2().then(d.hitch(this,function(b){var c=(a-1)*this.pageSize;b=b.slice(c,c+this.pageSize);return this._queryByObjectIds(b)}))},_queryPageForType3:function(a){return this._doQueryForQueryType3().then(d.hitch(this,function(b){var c=d.mixin({},b);c.features=[];var e=(a-1)*this.pageSize;c.features=(b.features||[]).slice(e,e+this.pageSize);return c}))},_tryLocaleNumber:function(a){var b=l.localizeNumber(a);if(null===
b||void 0===b)b=a;return b},_tryLocaleDate:function(a){var b=l.localizeDate(a);b||(b=a.toLocaleDateString());return b},_getLayerIndexByLayerUrl:function(a){var b=a.lastIndexOf("/");a=a.slice(b+1,a.length);return parseInt(a,10)},_getServiceUrlByLayerUrl:function(a){var b=a.lastIndexOf("/");return a.slice(0,b)},_isImageServiceLayer:function(a){return-1<a.indexOf("/ImageServer")},_isTable:function(a){return"Table"===a.type},_getObjectIdField:function(){return this.layerDefinition.objectIdField},_query:function(a){var b=
new f;b.where=a||this.query.where;b.geometry=this.query.geometry;b.outSpatialReference=this.map.spatialReference;b.returnGeometry=this.query.returnGeometry;b.spatialRelationship=this.query.spatialRelationship;b.outFields=this.query.outFields;return(new g(this.url)).execute(b)},_queryIds:function(){var a=new f;a.where=this.query.where;a.geometry=this.query.geometry;a.returnGeometry=!1;a.spatialRelationship=this.query.spatialRelationship;a.outSpatialReference=this.query.outSpatialReference;return(new g(this.url)).executeForIds(a).then(d.hitch(this,
function(a){a||(a=[]);return a}))},_queryByObjectIds:function(a){var b=new k,c=new f;c.returnGeometry=this.query.returnGeometry;c.outSpatialReference=this.query.outSpatialReference;c.spatialRelationship=this.query.spatialRelationship;c.outFields=this.query.outFields;c.objectIds=a;(new g(this.url)).execute(c).then(d.hitch(this,function(a){b.resolve(a)}),d.hitch(this,function(c){if(400===c.code){var e=this._getObjectIdField(),f="",g=a.length;h.forEach(a,d.hitch(this,function(a,b){f+=e+" \x3d "+a;b!==
g-1&&(f+=" OR ")}));this._query(f).then(d.hitch(this,function(a){b.resolve(a)}),d.hitch(this,function(a){b.reject(a)}))}else b.reject(c)}));return b},_queryCount:function(){var a=new f;a.where=this.query.where;a.geometry=this.query.geometry;a.outSpatialReference=this.query.outSpatialReference;a.spatialRelationship=this.query.spatialRelationship;a.returnGeometry=!1;return(new g(this.url)).executeForCount(a)},_queryWithPaginationAndOrder:function(a){var b=new f;b.where=this.query.where;b.geometry=this.query.geometry;
b.outSpatialReference=this.query.outSpatialReference;b.returnGeometry=this.query.returnGeometry;b.spatialRelationship=this.query.spatialRelationship;b.outFields=this.query.outFields;b.start=a;b.num=this.pageSize;(a=this.query.orderByFields)&&0<a.length&&(b.orderByFields=a,a=h.map(a,d.hitch(this,function(a){return a.split(" ")[0]})),h.forEach(a,d.hitch(this,function(a){0>b.outFields.indexOf(a)&&b.outFields.push(a)})));return(new g(this.url)).execute(b)}});e._isServiceSupportsOrderBy=function(a){var b=
!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsOrderBy&&(b=!0);return b};e._isServiceSupportsPagination=function(a){var b=!1;a.advancedQueryCapabilities&&a.advancedQueryCapabilities.supportsPagination&&(b=!0);return b};e._isSupportObjectIds=function(a){var b=0;a.currentVersion&&(b=parseFloat(a.currentVersion));return 10<=b||a.hasOwnProperty("typeIdField")};e.getQueryType=function(a){var b=-1;return b=e._isServiceSupportsOrderBy(a)&&e._isServiceSupportsPagination(a)?1:e._isSupportObjectIds(a)?
2:3};return e});