// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/lang dojo/_base/array dojo/Deferred esri/config esri/graphic esri/graphicsUtils esri/geometry/Extent esri/geometry/Point esri/SpatialReference esri/geometry/webMercatorUtils esri/tasks/ProjectParameters".split(" "),function(m,q,n,p,u,v,w,x,r,t,y){var d={zoomToFeatureSet:function(a,b,c){var e=b.features&&0<b.features.length&&b.features[0].getLayer&&b.features[0].getLayer(),e=e?e.id:null;b=d.graphicsExtent(b.features,c);return d.zoomToExtent(a,b,e)},zoomToExtent:function(a,b,c){var e;
if(!a||!d.isValidExtent(b))return e=new n,e.reject(),e;c?(e=new n,require(["jimu/LayerStructure"],function(g){(g=g.getInstance().getNodeById(c))?g.zoomTo(b).then(function(){e.resolve()},function(){e.reject()}):d.projectToMapSpatialReference(a,b).then(function(c){b.isSinglePoint&&(c=d.convertSinglePointExtent(a,c));a.setExtent(c,!0);e.resolve()},function(){e.reject()})})):e=d.projectToMapSpatialReference(a,b).then(function(c){b.isSinglePoint&&(c=d.convertSinglePointExtent(a,c));return a.setExtent(c,
!0)});return e},isValidExtent:function(a){return a&&d.isTrueOrZero(a.xmin)&&d.isTrueOrZero(a.ymin)&&d.isTrueOrZero(a.xmax)&&d.isTrueOrZero(a.ymax)}};d.isVaildExtent=d.isValidExtent;d.isTrueOrZero=function(a){return 0===a?!0:!!a};d.convertSinglePointExtent=function(a,b){var c=a.getScale();if(c=d.getMedianScale(a,c,0))b=d.adjustHeightToAspectRatio(a,b),b=d.getExtentForScale(b,a.width,c);return b};d.graphicsExtent=function(a,b){var c=null;try{if(a&&1===a.length&&"esri.geometry.Multipoint"===a[0].geometry.declaredClass&&
1===a[0].geometry.points.length){var e=a[0].geometry.points[0],d=new x(e[0],e[1],a[0].geometry.spatialReference);a=[new u(d)]}if(a&&1===a.length&&"esri.geometry.Point"===a[0].geometry.declaredClass){var f=a[0].geometry,c=new w(f.x-1E-4,f.y-1E-4,f.x+1E-4,f.y+1E-4,f.spatialReference);c.isSinglePoint=!0}else a&&0<a.length&&(c=v.graphicsExtent(a))&&"number"===typeof b&&0<b&&(c=c.expand(b))}catch(h){console.error(h)}return c};d.projectToMapSpatialReference=function(a,b){var c=new n,e=b;if(a&&b)if(a.spatialReference.equals(b.spatialReference))c.resolve(e);
else if(a.spatialReference.isWebMercator()&&b.spatialReference.equals(new r(4326)))e=t.geographicToWebMercator(b),e.isSinglePoint=b.isSinglePoint,c.resolve(e);else if(a.spatialReference.equals(new r(4326))&&b.spatialReference.isWebMercator())e=t.webMercatorToGeographic(b),e.isSinglePoint=b.isSinglePoint,c.resolve(e);else{var d=p&&p.defaults&&p.defaults.geometryService;if(d&&"esri.tasks.GeometryService"===d.declaredClass){var f=new y;f.geometries=[b];f.outSR=a.spatialReference;d.project(f).then(function(a){(e=
a&&0<a.length&&a[0])?(e.isSinglePoint=b.isSinglePoint,c.resolve(e)):c.reject()},function(){})}else c.reject()}else c.reject();return c};d.getMapLods=function(a){var b=null;a._params&&a._params.lods&&(b=q.map(a._params.lods,m.hitch(this,function(a){return a.toJson()})));return b};d.getMedianScale=function(a,b,c){return d.getTargetScale(a,2,b,c)};d.getTargetScale=function(a,b,c,e){a=d.getMapLods(a);var g=1;if(a){var f=[],h=[];q.forEach(a,function(a){0<c&&a.scale>c||(a.scale<e?h.push(a.scale):f.push(a.scale))});
f.reverse();1<=f.length?(g=h.length?h.length/a.length:1,b=Math.floor((f.length-1)/(b/g)),b=f[b]):b=null}else b=0===c?null:(c-e)/b;return b};d.getScaleForNextTileLevel=function(a,b,c){if(a=d.getMapLods(a)){if(c){for(c=0;c<a.length;c++)if(a[c].scale<b)return a[c].scale-1;return a[a.length-1].scale-1}for(c=a.length-1;0<=c;c--)if(a[c].scale>b)return a[c].scale+1;return a[0].scale+1}return c?b-1:b+1};d.adjustExtentToAspectRatio=function(a,b){a=a.width/a.height;var c=b.getWidth()/b.getHeight();c>a?(a=b.getWidth()/
a/2,m.mixin(b,{ymin:b.getCenter().y-a,ymax:b.getCenter().y+a})):c<a&&(a=b.getHeight()*a/2,m.mixin(b,{xmin:b.getCenter().x-a,xmax:b.getCenter().x+a}));return b};d.adjustHeightToAspectRatio=function(a,b){a=b.getWidth()*(a.height/a.width)/5;m.mixin(b,{ymin:b.getCenter().y-a,ymax:b.getCenter().y+a});return b};d.getExtentForScale=function(a,b,c){var d=20015077/180,g=esri.config.defaults,f=esri.WKIDUnitConversion,h,k,l=a.spatialReference;l&&(h=l.wkid,k=l.wkt);l=null;h?l=f.values[f[h]]:k&&-1!==k.search(/^PROJCS/i)&&
(f=/UNIT\[([^\]]+)\]\]$/i.exec(k))&&f[1]&&(l=parseFloat(f[1].split(",")[1]));return a.expand(c*b/(39.37*(l||d)*g.screenDPI)/a.getWidth())};d.getScaleForExtent=function(a,b){var c=20015077/180,d=esri.config.defaults,g=esri.WKIDUnitConversion,f,h,k=a.spatialReference;k&&(f=k.wkid,h=k.wkt);k=null;f?k=g.values[g[f]]:h&&-1!==h.search(/^PROJCS/i)&&(g=/UNIT\[([^\]]+)\]\]$/i.exec(h))&&g[1]&&(k=parseFloat(g[1].split(",")[1]));return a.getWidth()/b*(k||c)*39.37*d.screenDPI};return d});