// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/on dojo/string dojo/dom-attr dojo/dom-style dojo/_base/lang dojo/_base/array dojo/dom-construct esri/graphic jimu/dijit/Message dijit/_WidgetBase ./presetUtils".split(" "),function(q,r,l,t,k,m,f,n,g,u,p,v,w){return q([v,r],{newRelatedFeature:{},isSaveEnable:!1,postCreate:function(){this._createTable()},_createTable:function(){var a;a=g.create("div",{"class":"relatedTablesContainer"},this.domNode);n.forEach(this.relationshipInfo,f.hitch(this,function(b){b.featureLayer&&
b.hasOwnProperty("relationshipId")&&this._createRelatedTableItem(b,a)}))},_createRelatedTableItem:function(a,b){var c,e,d,h;d=this.layerInfosObj.getLayerOrTableInfoById(a.featureLayer.id);c=g.create("div",{"class":"relatedTableTitleContainer"},b);k.set(c,"layerId",d.id);k.set(c,"relationshipId",a.relationshipId);k.set(c,"parentFeatureOID",this.parentFeature.attributes[this.parentFeature._layer.objectIdField]);l(c,"click",f.hitch(this,function(){this.emit("titleClicked",d.id,a.relationshipId,!1,this.parentFeatureIndexInAI,
this.parentFeature.attributes[this.parentFeature._layer.objectIdField],this.newRelatedFeature[a.relationshipId].foreignKeyField)}));b=g.create("div",{"class":"relatedTableTitle esriCTEllipsis",innerHTML:d.title,title:d.title},c);this._createNewGraphics(a.relationshipId,d.id);this._canAddFeatures(a,d)&&"Table"===d.layerObject.type?(e=g.create("div",{"class":"relatedTableIcons itemTitleCreateNew",title:this.nls.addNewFeature},c),k.set(e,"tableId",d.id),l(e,"click",f.hitch(this,function(b){b.stopPropagation();
h=this.newRelatedFeature[a.relationshipId];this.isSaveEnable?p({message:this.nls.pendingFeatureSaveMsg}):void 0===this.parentFeature.attributes[h.primaryKeyField]||null===this.parentFeature.attributes[h.primaryKeyField]?(b=w.getFieldInfoByFieldName(this.parentFieldInfos,h.primaryKeyField).label||h.primaryKeyField,b=t.substitute(this.nls.invalidRelationShipMsg,{parentKeyField:b}),p({message:b})):(this.newRelatedFeature[a.relationshipId].attributes[this.newRelatedFeature[a.relationshipId].foreignKeyField]=
this.parentFeature.attributes[this.newRelatedFeature[a.relationshipId].primaryKeyField],this.emit("addRelatedRecord",this.newRelatedFeature[a.relationshipId],c,d.id,this.parentFeatureIndexInAI,this.newRelatedFeature[a.relationshipId].foreignKeyField))})),m.set(b,"width","calc(100% - 55px)")):m.set(b,"width","calc(100% - 30px)");g.create("div",{"class":"relatedTableIcons itemTitleNextArrow"},c)},_canAddFeatures:function(a,b){b=b.layerObject.getEditCapabilities();return!a.allowUpdateOnly&&a._editFlag&&
b.canCreate?!0:!1},_createNewGraphics:function(a,b){var c,e,d;c={};b=this.layerInfosObj.getLayerOrTableInfoById(b);0<b.layerObject.templates.length?c=b.layerObject.templates[0].prototype.attributes:0<b.layerObject.types.length&&(c=b.layerObject.types[0].templates[0].prototype.attributes);c=new u(null,null,f.clone(c));e=this._getRelationShipById(this.parentFeature._layer,a);d=this._getRelationShipById(b.layerObject,a);e=e.keyField;d=d.keyField;c.attributes.hasOwnProperty(d)&&(c.attributes[d]=this.parentFeature.attributes[e]);
this.newRelatedFeature[a]=c;this.newRelatedFeature[a].primaryKeyField=e;this.newRelatedFeature[a].foreignKeyField=d;this.newRelatedFeature[a].featureLayer=b},_getRelationShipById:function(a,b){var c;n.some(a.relationships,f.hitch(this,function(a){if(a.id===b)return c=a,!0}));return c},updateFeatureInstance:function(a){this.parentFeature&&(this.parentFeature.attributes=f.clone(a))}})});