// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./table/FeatureLayerQueryStore jimu/utils".split(" "),function(k,n,r,q,h,g,e,t,l,u,w,p){function v(f,c){if(!f||!f.length)return c||[];if(!c||!c.length)return f;for(var a=[],b=0,d=f.length;b<d;b++)for(var m=f[b],e=0,g=c.length;e<g;e++){var h=c[e];if(h.name===m.name){h.alias!==
m.alias&&(m.alias=h.alias);a.push(m);break}}return a}g.readLayerInfosObj=function(f){return r.getInstance(f,f.itemInfo)};g.readLayerInfosFromMap=function(f,c,a){var b=new q;r.getInstance(f,f.itemInfo).then(k.hitch(this,function(d){var m=[];c?d.traversalLayerInfosOfWebmap(function(b){m.push(b)}):d.traversal(function(b){m.push(b)});if(a){var f=[],e=d.getMapNotesLayerInfoArray();n.forEach(e,function(b){f.push(b.id);b.traversal(function(b){f.push(b.id)})});m=n.filter(m,function(b){return-1===f.indexOf(b.id)})}d=
d.getTableInfoArray();m=m.concat(d);b.resolve(m)}),k.hitch(this,function(d){console.error(d);b.reject(d)}));return b.promise};g.generateColumnsFromFields=function(f,c,a,b,d,m,e){function x(b){if(c&&u.isDefined(c.fieldInfos))for(var d=0,a=c.fieldInfos.length;d<a;d++){var m=c.fieldInfos[d];if(m.fieldName===b)return m.format}return null}var h={selectionHandle:{label:"",className:"selection-handle-column",hidden:!1,unhidable:!0,filed:"selection-handle-column",sortable:!1,_cache:{sortable:!1,statistics:!1}}};
n.forEach(a,k.hitch(g,function(a,c,l){c="field"+c;var t=!!a.domain,p="esriFieldTypeDate"===a.type,y=b&&a.name===b,q="esriFieldTypeDouble"===a.type||"esriFieldTypeSingle"===a.type||"esriFieldTypeInteger"===a.type||"esriFieldTypeSmallInteger"===a.type,z="esriFieldTypeString"===a.type,A=a.alias||a.name,r;r=1===l.length?!1:f&&f[c]?f[c].hidden:a?!a.show&&u.isDefined(a.show):!1;h[c]={label:A,className:c,hidden:r,unhidable:1===l.length?!1:!a.show&&u.isDefined(a.show)&&a._pk,field:a.name,sortable:!1,_cache:{sortable:!!m,
statistics:e&&!t&&q}};z?h[c].formatter=k.hitch(g,g.urlFormatter):p?h[c].formatter=k.hitch(g,g.dateFormatter,x(a.name)):q&&(h[c].formatter=k.hitch(g,g.numberFormatter,x(a.name)));t?h[c].get=k.hitch(g,function(b,a){return this.getCodeValue(b.domain,a[b.name])},a):y?h[c].get=k.hitch(g,function(b,a,d){return this.getTypeName(d[b.name],a)},a,d):t||p||y||(h[c].get=k.hitch(g,function(b,a,d,c){var m=null;a&&d&&0<d.length&&(d=(d=n.filter(d,k.hitch(g,function(b){return b.id===c[a]})))&&d[0]||null)&&d.domains&&
d.domains[b.name]&&d.domains[b.name].codedValues&&(m=this.getCodeValue(d.domains[b.name],c[b.name]));return(b=null!==m?m:c[b.name])||isFinite(b)?b:""},a,b,d))}));return h};g.getTypeName=function(f,c){return p.fieldFormatter.getTypeName(f,c)};g.getCodeValue=function(f,c){return p.fieldFormatter.getCodedValue(f,c)};g.urlFormatter=function(f){return p.fieldFormatter.getFormattedUrl(f)};g.dateFormatter=function(f,c){return p.fieldFormatter.getFormattedDate(c,f)};g.numberFormatter=function(f,c){return p.fieldFormatter.getFormattedNumber(c,
f)};g.readLayerObjectsFromMap=function(f,c,a){var b=new q,d=[];this.readLayerInfosFromMap(f,c,a).then(k.hitch(this,function(a){n.forEach(a,k.hitch(this,function(b){d.push(b.getLayerObject())}));h(d).then(k.hitch(this,function(a){b.resolve(a)}),k.hitch(this,function(a){b.reject(a);console.error(a)}))}),k.hitch(this,function(a){b.reject(a)}));return b.promise};g.readSupportTableInfoFromLayerInfos=function(f){var c=new q,a=[];n.forEach(f,k.hitch(this,function(b){a.push(b.getSupportTableInfo())}));h(a).then(k.hitch(this,
function(b){b=k.clone(b);n.forEach(b,function(b,a){b.id=f[a].id});c.resolve(b)}),function(b){c.reject(b)});return c.promise};g.readConfigLayerInfosFromMap=function(f,c,a){var b=new q,d=[];this.readLayerInfosFromMap(f,c,a).then(k.hitch(this,function(a){var c=[];n.forEach(a,function(a){d.push(a.getSupportTableInfo())});h(d).then(k.hitch(this,function(d){n.forEach(d,k.hitch(this,function(b,d){b.isSupportedLayer&&(a[d].name=a[d].title,c.push(a[d]))}));b.resolve(c)}),k.hitch(this,function(a){b.reject(a)}))}),
k.hitch(this,function(a){b.reject(a)}));return b.promise};g.getConfigInfosFromLayerInfos=function(f){return n.map(f,function(c){return g.getConfigInfoFromLayerInfo(c)})};g.getConfigInfoFromLayerInfo=function(f){var c={};c.name=f.name||f.title;c.id=f.id;c.show=f.isShowInMap();c.layer={url:f.getUrl()};var a=f.getPopupInfo();a&&!a.description&&(c.layer.fields=n.map(a.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,show:a.visible,format:a.format}}),f=k.getObject("layerObject.fields",!1,f),
c.layer.fields=v(c.layer.fields,f),n.some(c.layer.fields,function(a){return a.show})||(c.layer.fields&&0<c.layer.fields.length?c.layer.fields[0].show=!0:console.warn("We do not get fields info.")));return c};g.generateCacheStore=function(f,c,a,b,d){f=new w({layer:f,objectIds:f._objectIds||null,totalCount:c,batchCount:a,where:b||"1\x3d1",spatialFilter:d});c=new l;return new t(f,c,{})};g.generateMemoryStore=function(f,c){return new e(new l({data:f||[],idProperty:c}))};g.merge=function(f,c,a,b){for(var d=
n.map(c,function(b){return b[a]}),m=0,e=f.length;m<e;m++){var h=d.indexOf(f[m][a]);-1<h&&b(f[m],c[h])}};g.syncOrderWith=function(f,c,a){function b(a,b){return n.map(a,function(a){return a[b]})}if(!k.isArray(c)||!a)return f;for(var d=b(f,a),m=[],e=0,h=c.length;e<h;e++){var g=d.indexOf(c[e][a]);-1<g&&(m=m.concat(f.splice(g,1)),d=b(f,a))}return m.concat(f)}})},"dojo/store/Cache":function(){define(["../_base/lang","../when"],function(k,n){var r=function(q,h,g){g=g||{};return k.delegate(q,{query:function(e,
k){e=q.query(e,k);e.forEach(function(e){g.isLoaded&&!g.isLoaded(e)||h.put(e)});return e},queryEngine:q.queryEngine||h.queryEngine,get:function(e,g){return n(h.get(e),function(l){return l||n(q.get(e,g),function(g){g&&h.put(g,{id:e});return g})})},add:function(e,g){return n(q.add(e,g),function(l){h.add(l&&"object"==typeof l?l:e,g);return l})},put:function(e,g){h.remove(g&&g.id||this.getIdentity(e));return n(q.put(e,g),function(l){h.put(l&&"object"==typeof l?l:e,g);return l})},remove:function(e,g){return n(q.remove(e,
g),function(l){return h.remove(e,g)})},evict:function(e){return h.remove(e)}})};k.setObject("dojo.store.Cache",r);return r})},"widgets/AttributeTable/table/FeatureLayerQueryStore":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/tasks/query esri/tasks/QueryTask ./FeatureLayerQueryResult".split(" "),function(k,n,r,q,h,g){return k(null,{queryUrl:"",idProperty:"id",data:null,_entityData:null,constructor:function(e){k.safeMixin(this,e);this.data=[];this._entityData=[];this.layer=
e.layer;this.objectIds=e.objectIds;this.where=e.where;this.orderByFields=e.orderByFields;this.totalCount=e.totalCount;this.batchCount=e.batchCount||25;this.idProperty=this.layer.objectIdField;this.spatialFilter=e.spatialFilter;this.layer&&this.layer.url&&(this.queryTask=new h(this.layer.url))},get:function(e){return this.data[e]},getIdentity:function(e){return e[this.idProperty]},query:function(e,h){var l=new q,k=h&&h.start||0,t=h._export_count||this.batchCount,p=null;"function"===typeof e?p=e(this._entityData):
"[object Array]"===Object.prototype.toString.call(e)&&(p=e);this.objectIds?(p=p?p:this.objectIds,l.objectIds=p.length>=k+this.batchCount?p.slice(k,k+t):p.slice(k)):(p&&0<p.length?l.objectIds=p.length>=k+this.batchCount?p.slice(k,k+t):p.slice(k):(l.start=k,l.num=t,l.where=this.where,l.geometry=this.spatialFilter,l.spatialRelationship=q.SPATIAL_REL_INTERSECTS),(e=h.sort)&&0<e.length&&(e=r.map(e,function(f){return f.attribute+" "+(f.descending?"DESC":"ASC")}),l.orderByFields=e));l.returnGeometry="esriGeometryPoint"===
this.layer.geometryType;l.outFields=["*"];var v=this.totalCount;e=null;e=!l.where;if(!(l.objectIds&&0<l.objectIds.length)&&e)return new g([]);e=this.queryTask?this.queryTask.execute(l):this.layer.queryFeatures(l);e.total=e.then(n.hitch(this,function(f){var c=0,a=this.layer.objectIdField;if(this.objectIds){if(!a)for(c=0;c<f.fields.length;c++)if("esriFieldTypeOID"===f.fields[c].type){a=f.fields[c].name;break}for(var b={},c=0;c<f.features.length;c++)b[f.features[c].attributes[a]]=f.features[c];f.features=
r.map(l.objectIds,function(a){return b[a]})}for(c=0;c<f.features.length;c++)if(f.features[c]){var d=f.features[c];f.features[c]=n.mixin(n.clone(d.attributes),{geometry:d.geometry});this.data[f.features[c][a]]=f.features[c];this._entityData.push(f.features[c])}f=f.features;return v}),function(){console.log("FeatureLayerQueryStore queryFeatures failed.");return 0});return new g(e)}})})},"widgets/AttributeTable/table/FeatureLayerQueryResult":function(){define("esri/main dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/DeferredList dojo/_base/array".split(" "),
function(k,n,r,q){var h=function(g){function e(e){g[e]||(g[e]=function(){var k=arguments;return q.when(g,function(g){Array.prototype.unshift.call(k,g.features||g);return h(r[e].apply(r,k))})})}if(!g)return g;g.then&&(g=n.delegate(g));g.total||(g.total=q.when(g,function(e){return k._isDefined(e.total)?e.total:e.length||0}));e("forEach");e("filter");e("map");e("some");e("every");return g};return h})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv class\x3d"instruction"\x3e\r\n    \x3cp\x3e${nls.instruction}\x3c/p\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"table-options jimu-ellipsis"\x3e\r\n    \x3cul\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"exportcsv" checked\r\n        data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"expand" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.expand}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"filterByMapExtent" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.filterByExtent}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"textSelection" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.allowTextSelection}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n    \x3c/ul\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:14px; width: 100%; height: 100%; position: relative; color: #596679;}.jimu-widget-attributetable-setting .instruction{font-size: 12px; margin-bottom: 10px;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; height: 240px;}.jimu-widget-attributetable-setting .table-options ul{list-style-type: none; padding: 0;}.jimu-widget-attributetable-setting .jimu-checkbox{margin-right: 20px;}.jimu-widget-attributetable-setting .disable-checkbox{color: #e5e5e5;}",
"*now":function(k){k(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","bs","cs","da","de","en","el","es","et","fi","fr","he","hi","hr","id","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sl","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])},"*noref":1}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/query jimu/dijit/Popup jimu/dijit/Message jimu/dijit/CheckBox jimu/dijit/LoadingShelter ../utils".split(" "),function(k,n,r,q,h,g,e,t,l,u,w,p,v,f,c){return k([r,n],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,_allLayerFields:null,_layerInfos:null,_tableInfos:null,_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,
_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new q({fields:[{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"},{name:"label",title:this.nls.label,width:"60%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"20%",actions:["edit"],"class":"symbol"},{name:"showAttachments",title:"",type:"checkbox",hidden:!0}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);g.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.shelter=new f({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();
c.readLayerInfosObj(this.map).then(h.hitch(this,function(a){this.own(a.on("layerInfosChanged",h.hitch(this,this.onLayerInfosChanged)));this.own(t(this.displayFieldsTable,"actions-edit",h.hitch(this,this.editFieldsClick)));this.own(t(this.displayFieldsTable,"row-click",h.hitch(this,this._verifiedOnShowClick)));this.setConfig(this.config)}))},editFieldsClick:function(a){var b=u(".action-item-parent",a);if(b&&b.length)if(b=this.displayFieldsTable.getRowData(a),b.show){var d=parseInt(b.index,10);this.shelter.show();
this._getLayerFields(d).then(h.hitch(this,function(b){this.openFieldsDialog(a,b,d)}),h.hitch(this,function(a){console.error(a)})).always(h.hitch(this,function(){this.shelter.hide()}))}else var c=new p({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:h.hitch(this,function(){c.close()})}]})},_verifiedOnShowClick:function(a){var b=this.displayFieldsTable.getRowData(a),d=parseInt(b.index,10),c=null,c=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[d]:
this._layerInfos[d],d=-1<this._unSpportQueryCampsite.layerNames.indexOf(c.name||c.title);b.show&&d&&(new p({message:this.nls.unsupportQueryWarning}),b.show=!1,this.displayFieldsTable.editRow(a,b))},_getLayerFields:function(a){return this._layerInfos[a].getLayerObject().then(h.hitch(this,function(b){var d=this._allLayerFields[a];b=e.map(b.fields,function(a){return{name:a.name,alias:a.alias,show:!0}});c.merge(b,d,"name",function(a,b){h.mixin(a,b)});return b=c.syncOrderWith(b,d,"name")}))},openFieldsDialog:function(a,
b,d){var c=!1,e=this._layerInfos[d];(e=e&&e.layerObject)&&(c=e.hasAttachments&&e.objectIdField);var e=g.create("div"),f=this._createFieldsTable(b,d);g.place(f.domNode,e);var k=null;c&&(k=new v({label:this.nls.showAttachments,style:"margin-top:10px;"}),b=this.displayFieldsTable.getRowData(a),k.setValue(b.showAttachments),k.placeAt(e));this.currentFieldTable=f;b=600;k&&(b=640);var l=new w({titleLabel:this.nls.configureLayerFields,width:640,maxHeight:b,autoHeight:!0,content:e,buttons:[{label:this.nls.ok,
onClick:h.hitch(this,function(){this._allLayerFields[d]=f.getData();var b=k?k.getValue():!1;this.displayFieldsTable.editRow(a,{showAttachments:b});l.close();l=null})},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],onClick:h.hitch(this,function(){l.close();l=null})}],onClose:function(){l=null}});f.startup()},_createFieldsTable:function(a){for(var b=null,d={fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show",onChange:h.hitch(this,function(a){var d=b.getData();
!e.some(d,h.hitch(this,function(a){return a.show}))&&(new p({message:this.nls.fieldCheckWarning}),d=b.getRowData(a))&&(d.show=!0,b.editRow(a,d))})},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}},b=new q(d),d=0;d<a.length;d++)a[d].show=void 0===a[d].show?!0:!!a[d].show,
b.addRow(a[d]);return b},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this._processTableData().then(h.hitch(this,function(a){this._init(a);this.shelter.hide()}),h.hitch(this,function(a){new p({message:a.message||a})}))},onLayerInfosChanged:function(a,b,d){"added"===b&&d&&a&&d.getSupportTableInfo().then(h.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?this._delayedLayerInfos.push(d):this._layerInfos&&0<this._layerInfos.length&&
!this._getLayerInfoById(d.id)&&(this._delayedLayerInfosAfterInit.push(d),this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var b=this._layerInfos.length,d=0;d<a.length;d++){var e=c.getConfigInfoFromLayerInfo(a[d]);this.displayFieldsTable.addRow({label:e.name||e.title,url:e.layer.url,index:""+(b+d),show:e.show});this._allLayerFields.push(e.layer.fields);this._layerInfos.push(a[d])}},_processDelayedLayerInfos:function(){0<
this._delayedLayerInfos.length&&(e.forEach(this._delayedLayerInfos,h.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new l;c.readConfigLayerInfosFromMap(this.map,!0,!0).then(h.hitch(this,function(b){this._layerInfos=b;this._processDelayedLayerInfos();c.readSupportTableInfoFromLayerInfos(this._layerInfos).then(h.hitch(this,function(d){this._tableInfos=d;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?
(d=c.getConfigInfosFromLayerInfos(this._layerInfos),c.merge(d,this.config.layerInfos,"id",h.hitch(this,function(a,b){a.show=b.show;a.showAttachments=b.showAttachments;a.layer.url=b.layer.url;h.getObject("layer.fields.length",!1,a)&&h.getObject("layer.fields.length",!1,b)?(c.merge(a.layer.fields,b.layer.fields,"name",function(a,b){h.mixin(a,b)}),a.layer.fields=c.syncOrderWith(a.layer.fields,b.layer.fields,"name")):a.layer.fields=b.layer.fields})),this.config.layerInfos=d,this._unSpportQueryCampsite.fromConfig=
!0,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this.config.layerInfos),a.resolve(d)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(c.getConfigInfosFromLayerInfos(b)))}),function(b){console.error(b);a.reject(b)})}),h.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_getUnsupportQueryLayerNames:function(a){var b=[];e.forEach(a,h.hitch(this,function(a){var d=
this._getSupportTableInfoById(a.id);d&&!d.isSupportQuery&&b.push(a.name||a.title)}));return b},_init:function(a){for(var b=[],d=0;d<a.length;d++){var c=a[d].show&&this._getSupportTableInfoById(a[d].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[d].name||a[d].title,url:a[d].layer.url,index:""+d,show:c,showAttachments:!!a[d].showAttachments});this._allLayerFields.push(a[d].layer.fields);this._unSpportQueryCampsite.fromConfig&&(c=(c=this._unSpportQueryCampsite.layerNames)&&-1<c.indexOf(a[d].name||
a[d].title),a[d].show&&c&&b.push(a[d].name||a[d].title))}this._unSpportQueryCampsite.fromConfig&&0<b.length&&new p({message:this.nls.unsupportQueryLayers+"\x3cbr\x3e\x3cbr\x3e"+b.toString()});this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check();this.config.initiallyExpand?this.expand.check():this.expand.uncheck();this._canUseOpenAtStart()&&(this.openAtStart?this.expand.check():this.expand.uncheck(),this.expand.status=!1,g.addClass(this.expand.domNode,"disable-checkbox"));this.config.filterByMapExtent?
this.filterByMapExtent.check():this.filterByMapExtent.uncheck();this.config.allowTextSelection?this.textSelection.check():this.textSelection.uncheck()},_canUseOpenAtStart:function(){return this.closeable||!this.isOnScreen},_getLayerInfoById:function(a){for(var b=0,d=this._layerInfos.length;b<d;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,d=this._tableInfos.length;b<d;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){var a=
this.displayFieldsTable.getData(),b=[],d=a.length;if(this.config&&this.config.layerInfos&&0<this.config.layerInfos.length)e.forEach(a,h.hitch(this,function(c,d){c=this.config.layerInfos[d];var e={};e.name=c.name||c.title;e.id=c.id;e.layer={};e.layer.url=a[d].url;e.layer.fields=this._allLayerFields[d];e.show=a[d].show;e.showAttachments=a[d].showAttachments;b.push(e)}));else for(var c=0;c<d;c++){var f={};f.name=this._layerInfos[c].name||this._layerInfos[c].title;f.id=this._layerInfos[c].id;f.layer=
{};f.layer.url=a[c].url;f.layer.fields=this._allLayerFields[c];f.show=a[c].show;f.showAttachments=a[c].showAttachments;b.push(f)}this.config.layerInfos=b;this.config.hideExportButton=!this.exportcsv.getValue();this.config.filterByMapExtent=this.filterByMapExtent.getValue();this.config.allowTextSelection=this.textSelection.getValue();this._canUseOpenAtStart()||(this.config.initiallyExpand=this.expand.getValue());return this.config}})});