// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dijit/_WidgetBase dojo/on dojo/_base/lang dojo/Deferred esri/layers/FeatureLayer jimu/clientStatisticsUtils jimu/_chartHelpUtils".split(" "),function(l,m,n,g,p,k,h,q){return l([m],{postMixInProperties:function(){this.nls=window.jimuNls.statisticsChart},constructor:function(a){this.map=a.map;this.chartHelpUtils=new q({map:this.map,clientStatisticsUtils:h})},getChartOption:function(a,b,d,c){d=this.chartHelpUtils.getClientStatisticUtilsOptions(a,d,c);c=d.layerOption;c.featureLayer&&
this.chartHelpUtils.setLayerFeatureLayer(c.featureLayer);c.popupFieldInfos&&this.chartHelpUtils.setPopupInfo(c.popupFieldInfos);d=this._getClientStatisticsData(d.csuOptions);a.features=a.features.filter(function(a){return!!a.attributes});this.chartHelpUtils.bindChartEvent(b,a,d);return this.getChartOptionWithData(a,d)},_getClientStatisticsData:function(a){var b=h.getClietStatisticsData(a),b=h.sortClientStatisticsData(b,a),b=h.getDataForMaxLabels(b,a.maxLabels);return b=this.chartHelpUtils.keepStatisticsDataBestDecimalPlace(a,
b,a.mode)},getLoadedLayer:function(a){return this._getLoadedLayer(a)},getChartOptionWithData:function(a,b){b=this.createOptionSeries(a,b);this._assigneeSettingColorToSeries(b,a);this.chartHelpUtils.updateChartSeriesDisplayName(b,a.chartConfig);return this._mapSettingConfigToChartOption(b,a)},_assigneeSettingColorToSeries:function(a,b){if(!a||!a.series)return a;this.chartHelpUtils.assigneeSettingColor(b.chartConfig,a.series,b.featureLayerForChartSymbologyChart)},createOptionSeries:function(a,b){var d=
a.chartConfig,c=d.type;a=d.mode;var d=d.valueFields,e=[],e="count"===a?[""]:"field"===a?[""]:g.clone(d),f=null,f={type:c,labels:[],series:[]};f.series=e.map(g.hitch(this,function(a){return{name:a,type:c,data:[]}}));b.forEach(g.hitch(this,function(a){var b=a.label;f.labels.push(b);for(var c=0;c<a.values.length;c++){var d={value:a.values[c],name:b,unit:a.unit};a.features&&(d.features=a.features);f.series[c].data.push(d)}}));return f},getLoadedLayerForSTD:function(a,b){a=this.mockLayerDefinitionForSTD(a,
b);return this._getLoadedLayer(a)},mockLayerDefinitionForSTD:function(a,b){var d={type:"Table",fields:[]},c=a.fields,e=b.mode;"category"===e||"field"===e?d.fields=a.fields:"count"===e&&d.fields.push({name:"STAT_COUNT",type:"esriFieldTypeInteger",alias:this.nls.count});"category"!==e&&"count"!==e||c.some(g.hitch(this,function(a){return a.name===b.categoryField?(d.fields.push(a),!0):!1}));return d},_getLoadedLayer:function(a){var b=new p,d=null,d="string"===typeof a?new k(a):"esri.layers.FeatureLayer"===
a.declaredClass?a:new k({layerDefinition:g.clone(a),featureSet:null});d.loaded?b.resolve(d):this.own(n(d,"load",g.hitch(this,function(){b.resolve(d)})));return b},_mapSettingConfigToChartOption:function(a,b,d){var c=b.chartConfig,e=c.type;b=c.mode;var f=["column","bar","line"];d={type:e,dataZoom:["inside","slider"],confine:!0,backgroundColor:c.backgroundColor,legend:c.showLegend,theme:d||"light",advanceOption:function(a){c.showLegend&&a.legend&&(a.legend.textStyle||(a.legend.textStyle={}),a.legend.textStyle.color=
c.legendTextColor,a.legend.textStyle.fontSize=c.legendTextSize);"pie"===e?a.series&&0<a.series.length&&a.series.forEach(g.hitch(this,function(a){"pie"===a.type&&(a.label||(a.label={}),a.label.normal||(a.label.normal={}),a.label.normal.show=c.showDataLabel,a.label.normal.textStyle||(a.label.normal.textStyle={}),a.label.normal.textStyle.color=c.dataLabelColor,a.label.normal.textStyle.fontSize=c.dataLabelSize)})):(a.xAxis||(a.xAxis={}),a.xAxis.axisLabel||(a.xAxis.axisLabel={}),a.xAxis.axisLabel.textStyle||
(a.xAxis.axisLabel.textStyle={}),a.xAxis.axisLabel.textStyle.color=c.horizontalAxisTextColor,a.xAxis.axisLabel.textStyle.fontSize=c.horizontalAxisTextSize,a.yAxis||(a.yAxis={}),a.yAxis.axisLabel||(a.yAxis.axisLabel={}),a.yAxis.axisLabel.textStyle||(a.yAxis.axisLabel.textStyle={}),a.yAxis.axisLabel.textStyle.color=c.verticalAxisTextColor,a.yAxis.axisLabel.textStyle.fontSize=c.verticalAxisTextSize)}};if("pie"===e)"field"!==b&&(b=c.seriesStyle)&&b.styles&&b.styles[0]&&(b=b.styles[0].style)&&Array.isArray(b.color)&&
(f=g.clone(b.color),2===f.length&&(f=this.chartHelpUtils.getColors(g.clone(b.color),6)),d.color=f),d.innerRadius=c.innerRadius,d.labelLine=!!c.showDataLabel;else if(-1<f.indexOf(e)){c.stack||(c.stack=!1);if("column"===e||"bar"===e||"line"===e&&c.area)d.stack=c.stack;"line"!==e||c.area||(c.area=!1);"line"===e&&(d.area=c.area);a.axisPointer=!0;a.scale=!1;a.hidexAxis=!c.showHorizontalAxis;a.hideyAxis=!c.showVerticalAxis}g.mixin(a,d);return a}})});