// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/on dojo/Evented dojo/Deferred dojo/promise/all dojo/_base/declare dijit/_WidgetBase dijit/_TemplatedMixin dijit/_WidgetsInTemplateMixin dojo/_base/lang dojo/_base/html dojo/_base/array dojo/query dijit/registry jimu/filterUtils jimu/utils ./_SingleFilterParameter ./_filter/ValueProviderFactory".split(" "),function(p,q,r,t,u,v,w,x,f,m,h,n,y,z,A,B,C){return u([v,w,x,q],{baseClass:"jimu-filter-parameters",templateString:'\x3cdiv\x3e\x3ctable style\x3d"width:100%;border-collapse:collapse;"\x3e\x3ctbody data-dojo-attach-point\x3d"tbody"\x3e\x3c/tbody\x3e\x3c/table\x3e\x3c/div\x3e',
_filterUtils:null,_spObj:null,nls:null,partsObj:null,layerInfo:null,OPERATORS:null,url:null,featureLayerId:null,postMixInProperties:function(){this.nls=window.jimuNls.filterBuilder;this._filterUtils=new z;this.OPERATORS=f.clone(this._filterUtils.OPERATORS);this._spObj={}},destroy:function(){this.clear();this._filterUtils=null;this.inherited(arguments)},getFilterExpr:function(a){var b=this._getNewValidPartsObj(this.partsObj,!0),d=b?this._getFilterExprByPartsObj(b):null;return a&&a.ifDisplaySQL?void 0===
b.displaySQL?d:b.displaySQL:d},getValueProviders:function(){for(var a=[],b=this._getAllInteractiveSinglePartArray(this.partsObj),d=0;d<b.length;d++){var c=b[d].spId;c&&(c=this._getSingleFilterParameterBySpId(c),a.push(c))}return a},_getNewValidPartsObj:function(a,b){a=f.clone(a);for(var d={logicalOperator:a.logicalOperator,parts:[]},c=f.hitch(this,function(a){if(a.spId){var b=this._getSingleFilterParameterBySpId(a.spId);a.valueObj=b.getValueObject();return b.getStatus()}return a.valueObj?1:-1}),e=
f.hitch(this,function(a){var b=c(a);0<b&&d.parts.push(a);return b}),g=f.hitch(this,function(a){var b=[];a.parts=h.filter(a.parts,f.hitch(this,function(a){a=c(a);b.push(a);return 0<a}));1===a.parts.length?d.parts.push(a.parts[0]):2<=a.parts.length&&d.parts.push(a);return Math.min.apply(b,b)}),k=0;k<a.parts.length;k++){var l=a.parts[k];if(l.parts){if(0>g(l)&&b)return null}else if(0>e(l)&&b)return null}return d},_getFilterExprByPartsObj:function(a){this._filterUtils.isHosted=A.isHostedService(this.url);
return this._filterUtils.getExprByFilterObj(a)},_getSingleFilterParameterBySpId:function(a){return this._spObj[a]},_getCascadeFilterPartsObj:function(a){var b={logicalOperator:this.partsObj.logicalOperator,parts:[]},d=f.clone(this.partsObj),c,e,g;c="none";a.interactiveObj&&a.interactiveObj.cascade&&(c=a.interactiveObj.cascade);if("previous"===c)for(c=0;c<d.parts.length;c++)e=d.parts[c],e.majorCascadeIndex<a.majorCascadeIndex?b.parts.push(e):e.parts&&e.majorCascadeIndex===a.majorCascadeIndex&&(g=f.clone(e),
g.parts=h.filter(g.parts,f.hitch(this,function(b){return b.minorCascadeIndex<a.minorCascadeIndex})),b.parts.push(g));else if("all"===c)for(c=0;c<d.parts.length;c++)e=d.parts[c],e.majorCascadeIndex!==a.majorCascadeIndex?b.parts.push(e):e.majorCascadeIndex===a.majorCascadeIndex&&e.parts&&(g=f.clone(e),h.some(e.parts,f.hitch(this,function(b){return b.spId===a.spId}))&&(g.parts=h.filter(g.parts,f.hitch(this,function(b){return b.minorCascadeIndex!==a.minorCascadeIndex})),b.parts.push(g)));return b=this._getNewValidPartsObj(b,
!1)},_getCascadeFilterExpr:function(a){var b="1\x3d1";(a=this._getCascadeFilterPartsObj(a))&&(b=this._getFilterExprByPartsObj(a));b||(b="1\x3d1");return b},clear:function(){this.featureLayerId=this.url=null;var a=n(".jimu-widget-query-single-parameter",this.tbody);h.forEach(a,f.hitch(this,function(a){y.byNode(a).destroy()}));m.empty(this.tbody);this.layerInfo=this.partsObj=null},build:function(a,b,d,c){var e=new r;this.clear();this.url=a;this.layerInfo=b;this.partsObj=f.clone(d);this.partsObj=this._updatePartsObj(this.partsObj);
this.featureLayerId=c;this._setCascadeIndexForPartsObj(this.partsObj);a=this._getAllInteractiveSinglePartArray(this.partsObj);if(0<a.length){var g=new C({url:this.url,layerDefinition:b,featureLayerId:this.featureLayerId});a=h.map(a,f.hitch(this,function(a){var d=m.create("tr",{innerHTML:"\x3ctd\x3e\x3c/td\x3e"},this.tbody),d=n("td",d)[0],c=this._getFieldInfo(a.fieldObj.name,this.layerInfo),c=new B({nls:this.nls,url:this.url,layerDefinition:b,fieldInfo:c,part:a,valueProviderFactory:g});this.own(p(c,
"change",f.hitch(this,this._onSingleFilterParameterChanged)));c.placeAt(d);c.startup();a.spId=c.id;return this._spObj[c.id]=c}));h.forEach(a,f.hitch(this,function(a){a.valueProvider.getCascadeFilterExpr=f.hitch(this,this._getCascadeFilterExpr,a.part);a.valueProvider.getCascadeFilterPartsObj=f.hitch(this,this._getCascadeFilterPartsObj,a.part)}));a=h.map(a,f.hitch(this,function(a){return a.init()}));t(a).then(f.hitch(this,function(){e.resolve()}),f.hitch(this,function(){e.reject()}))}else e.resolve();
return e},_updatePartsObj:function(a){h.forEach(a,f.hitch(this,function(a){a.parts?h.forEach(a.parts,f.hitch(this,function(a){a.interactiveObj&&!0===a.interactiveObj.cascade?a.interactiveObj.cascade="previous":!1===a.interactiveObj.cascade&&(a.interactiveObj.cascade="none")})):a.interactiveObj&&!0===a.interactiveObj.cascade?a.interactiveObj.cascade="previous":!1===a.interactiveObj.cascade&&(a.interactiveObj.cascade="none")}));return a},_setCascadeIndexForPartsObj:function(a){for(var b=0;b<a.parts.length;b++){var d=
a.parts[b];d.majorCascadeIndex="AND"===a.logicalOperator?b:0;d.minorCascadeIndex=0;d.cascadeIndex=d.majorCascadeIndex;if(d.parts)for(var c=0;c<d.parts.length;c++){var e=d.parts[c];e.majorCascadeIndex=d.majorCascadeIndex;e.minorCascadeIndex="AND"===d.logicalOperator?c:0;e.cascadeIndex=parseFloat(e.majorCascadeIndex+"."+e.minorCascadeIndex)}}},_getFieldInfo:function(a,b){b=b.fields;for(var d=0;d<b.length;d++){var c=b[d];if(a===c.name)return c}return null},_getAllInteractiveSinglePartArray:function(a){for(var b=
[],d=0;d<a.parts.length;d++){var c=a.parts[d];if(c.parts)for(var e=0;e<c.parts.length;e++){var f=c.parts[e];f.interactiveObj&&b.push(f)}else c.interactiveObj&&b.push(c)}return b},_onSingleFilterParameterChanged:function(){this.emit("change",this.getFilterExpr(!1))}})});