// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://@sbaseurl@/jsapi/jsapi/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/Deferred dojo/DeferredList jimu/utils esri/request esri/geometry/webMercatorUtils esri/geometry/Polygon esri/geometry/Polyline jimu/portalUtils jimu/tokenUtils jimu/dijit/Message".split(" "),function(r,e,l,d,m,t,h,u,v,w,x,n,p){return r("Snapshot",null,{_portal:null,_portalUrl:"",_layerArray:[],_originMapId:"",_originAppId:"",_credential:null,name:"",appendTimeStamp:null,baseMap:null,tags:"",description:"",shareWith:null,logo:"",time:null,
constructor:function(b,a){this.map=a;this.appConfig=b;this._originAppId=b.appId;this._originMapId=a.itemId;this._mapItemInfo=a.itemInfo;this._portalUrl=b.portalUrl;this._portal=x.getPortal(this._portalUrl);this._baseUrl=this._portalUrl+"sharing/rest/";this.nls=e.mixin({},window.jimuNls.drawBox,window.jimuNls.snapshot)},createSnapShot:function(b){this.ids=[];this.layerArray=[];this.time=this._getDateString(Date.now());this.name=(b.appendTimeStamp&&b.name?b.name+"_"+this.time:b.name)||this._mapItemInfo.item.title+
"_"+this.time;this.extent=b.mapExtent||this.map.extent;this.logo=b.logo||this.appConfig.logo;this.mapName=b.mapTitle||this.name;this.shareWith=b.shareWith||{everyone:!1,org:!1,groups:""};var a=b.folderOptions;a.name=b.folderOptions.name||this.name;a.title=b.folderOptions.title||this.name;a.description=b.folderOptions.description||this.name;b=b.data.reverse();return this._createSnapshot(a,b)},_createSnapshot:function(b,a){var c=new d;this._portal.getUser().then(e.hitch(this,this._processUser),function(a){c.reject(a)}).then(e.hitch(this,
this._createFolder,b),function(a){c.reject(a)}).then(e.hitch(this,this._createItems,a),function(a){c.reject(a)}).then(e.hitch(this,this._addLayers),function(a){c.reject(a)}).then(e.hitch(this,this._createMap,this._mapItemInfo),function(a){c.reject(a)}).then(e.hitch(this,this._processMap),function(a){c.reject(a)}).then(e.hitch(this,this._shareItems),function(a){c.reject(a)}).then(e.hitch(this,this._showMessage),function(a){c.reject(a)}).then(function(){c.resolve()});return c},_processUser:function(b){var a=
new d;this.user=b;this.groups=b.groups;a.resolve();return a},_createFolder:function(b){var a=new d;b={url:this._baseUrl+"content/users/"+this.user.username+"/createFolder",content:e.mixin({f:"json"},b),handleAs:"json",callbackParamName:"callback"};this._isValidCredential()&&(b.content.token=this._credential.token);h(b,{usePost:!0}).then(e.hitch(this,function(b){b.success?((this.folder=b.folder)&&this.folder.id&&this.ids.push(this.folder.id),a.resolve(b.folder)):(console.log(b),a.reject(b))}),e.hitch(this,
function(b){a.reject(b)}));return a},_createItems:function(b){var a=new d,c=[];l.forEach(b,e.hitch(this,function(a){a.graphics&&0<a.graphics.length&&c.push(this._createLayerItem(a))}));var f=[];(new m(c)).then(e.hitch(this,function(b){for(var c=0;c<b.length;c++)f.push(b[c][1]);a.resolve(f)}),e.hitch(this,function(b){a.reject(b)}));return a},_addLayers:function(b){for(var a=new d,c=[],f=0;f<b.length;f++)c.push(this.user.addItem(b[f],this.folder.id));var q=[];(new m(c)).then(e.hitch(this,function(b){for(var c=
0;c<b.length;c++){var f=b[c][1];f.success&&(q.push(f.id),this.ids.push(f.id))}a.resolve(q)}),e.hitch(this,function(b){a.reject(b)}));return a},_createMap:function(b,a){var c=b.itemData;b=this.name;for(var f,e=[],g=0;g<c.baseMap.baseMapLayers.length;g++)f=c.baseMap.baseMapLayers[g],e.push({id:f.id,layerType:f.layerType,url:f.url,visibility:f.visibility,opacity:f.opacity,title:f.title}),f=f.resourceInfo.spatialReference;c={baseMapLayers:e};e=[];for(g=0;g<this.layerArray.length;g++){var d=this.layerArray[g];
e.push({id:d.layer.id,layerType:"ArcGISFeatureLayer",visibility:d.layer.visible,opacity:d.layer.opacity,title:d.label,type:"Feature Collection",itemId:a[g]})}a=u.webMercatorToGeographic(this.extent);a={title:b,type:"Web Map",item:b,extent:a.xmin+","+a.ymin+","+a.xmax+","+a.ymax,text:JSON.stringify({operationalLayers:e,baseMap:c,spatialReference:f,version:"2.4"}),tags:this.name+","+this.nls.snapshot_append,wabType:"HTML"};return this.user.addItem(a,this.folder.id)},_processMap:function(b){var a=new d;
b.id&&this.ids.push(b.id);b.success?a.resolve(b.id):a.reject("fail");return a},_shareItems:function(b){var a=new d,c={url:this._baseUrl+"content/users/"+this.user.username+"/shareItems",content:{f:"json",everyone:this.shareWith.everyone,org:this.shareWith.org,items:this.ids.join(),groups:this.shareWith.groups,confirmItemControl:this._validateGroupItemControl(this.shareWith.groups)},handleAs:"json",callbackParamName:"callback"};this._isValidCredential()&&(c.content.token=this._credential.token);h(c,
{usePost:!0}).then(e.hitch(this,function(c){c.results&&0<c.results.length?a.resolve(this._portalUrl+"home/webmap/viewer.html?webmap\x3d"+b):a.reject("fail")}),e.hitch(this,function(b){a.reject(b)}));return a},_validateGroupItemControl:function(b){var a=b.split(",");return 0<this.groups.filter(function(b){var c=b.capabilities||[];return-1<a.indexOf(b.id)&&-1<c.indexOf("updateitemcontrol")}).length},_showMessage:function(b){var a=new d;"fail"===b?(new p({message:this.nls.snapshot_failed}),a.reject(b)):
(new p({message:'\x3ca href\x3d"'+b+'" target\x3d"_blank"\x3e'+this.nls.snapshot_complete+"\x3c/a\x3e"}),a.resolve("success"));return a},_getDateString:function(b){b=new Date(b);var a=b.getTimezoneOffset();return t.fieldFormatter.getFormattedDate(b,{dateFormat:"shortDateShortTime"})+" "+this.nls.utc+(0>a?"+"+Math.abs(a)/60:"-"+a/60)},_checkCredential:function(){var b=n.isValidCredential(this._credential);b||this._clearCredential();return b},_isValidCredential:function(){this._updateCredential();return this._checkCredential()},
_updateCredential:function(){this._checkCredential()||(this._credential=n.getPortalCredential(this._portalUrl))},_clearCredential:function(){this._credential=null},_createLayerItem:function(b){var a=new d;b=this._createLayer(b.graphics,e.mixin({},{description:b.name,name:b.name,tags:[b.name]},b));a.resolve(b);return a},_createLayer:function(b,a){var c=this.nls,e=this.time,d=b[0],g={point:"esriGeometryPoint",polyline:"esriGeometryPolyline",polygon:"esriGeometryPolygon"}["undefined"!==typeof d.geometry?
d.geometry.type:d.type],d=d.symbol?d.symbol.toJson():"",m=[],h=[{name:"ObjectID",alias:"ObjectID",type:"esriFieldTypeOID"},{name:c.snapshot_append,alias:c.snapshot_append,type:"esriFieldTypeString"}];a.fields&&0<a.fields.length&&l.forEach(a.fields,function(a){h.push({name:a.name,alias:a.alias,type:a.type,domain:a.domain})});var n=0;l.forEach(b,function(b){var d;switch(g){case "esriGeometryPolyline":d=b.geometry.paths;break;case "esriGeometryPolygon":d=b.geometry.rings;break;case "esriGeometryPoint":d=
[b.geometry]}var f=0,k;l.forEach(d,function(d){switch(g){case "esriGeometryPolyline":k=new w(d);k.spatialReference=b.geometry.spatialReference;break;case "esriGeometryPolygon":k=new v(d);k.spatialReference=b.geometry.spatialReference;break;case "esriGeometryPoint":k=d}var h={attributes:{ObjectID:n+f},geometry:k};h.attributes[c.snapshot_append]=e;a.fields&&0<a.fields.length&&l.forEach(a.fields,function(a){h.attributes[a.name]=b.attributes[a.name]});m.push(h);f+=1});n+=1});b={xmin:this.extent.xmin,
ymin:this.extent.ymin,xmax:this.extent.xmax,ymax:this.extent.ymax,spatialReference:this.extent.spatialReference};d=a.renderer&&a.renderer.toJson?a.renderer.toJson():a.renderer?JSON.stringify(a.renderer):{type:"simple",label:"",description:"",symbol:d};this.layerArray.push({layer:{id:a.name,label:a.name,opacity:1,visible:a.visibleOnStartup},label:a.name});return{title:a.name,type:"Feature Collection",tags:a.tags,description:a.description,extent:b,name:a.name,text:JSON.stringify({layers:[{layerDefinition:{name:a.name,
geometryType:g,objectIdField:"ObjectID",typeIdField:a.typeIdField,types:a.types,type:"Feature Layer",extent:b,drawingInfo:{renderer:d},fields:h,minScale:a.minScale,maxScale:a.maxScale},popupInfo:a.infoTemplate&&a.infoTemplate.info?a.infoTemplate.info:a.infoTemplate?a.infoTemplate:void 0,featureSet:{features:m,geometryType:g}}]}),f:"json"}}})});