// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/PublicNotification/setting/nls/strings":{searchSourceSetting:{title:"Haun ja puskurin asetukset",mainHint:"Voit ottaa k\u00e4ytt\u00f6\u00f6n osoitteiden ja kohteiden tekstihaut, geometrian digitoinnin ja puskuroinnin."},addressSourceSetting:{title:"Osoitekarttatasot",mainHint:"Voit m\u00e4\u00e4ritt\u00e4\u00e4, mitk\u00e4 vastaanottajan osoitetarran karttatasot ovat k\u00e4ytett\u00e4viss\u00e4."},notificationSetting:{title:"Ilmoitusasetukset",mainHint:"Voit m\u00e4\u00e4ritt\u00e4\u00e4 k\u00e4ytett\u00e4viss\u00e4 olevien ilmoitusten tyypit."},
groupingLabels:{addressSources:"Karttataso, jota k\u00e4ytet\u00e4\u00e4n vastaanottajakarttatasojen valintaan",averyStickersDetails:"Avery(r)-tarrat",csvDetails:"Pilkuin erotetut arvot (CSV) -tiedosto",drawingTools:"Piirtoty\u00f6kalut alueen m\u00e4\u00e4ritt\u00e4mist\u00e4 varten",featureLayerDetails:"Kohdekarttataso",geocoderDetails:"Geokooderi",labelFormats:"K\u00e4ytett\u00e4viss\u00e4 olevat osoitetarramuodot",printingOptions:"Tulostettujen osoitetarrasivujen asetukset",searchSources:"Etsi l\u00e4hteit\u00e4",
stickerFormatDetails:"Osoitetarrasivun parametrit"},hints:{alignmentAids:"Osoitetarrasivulle lis\u00e4tyt merkinn\u00e4t, joiden avulla sivu on helppo asemoida tulostimeen",csvNameList:"Kentt\u00e4nimien pilkuin eroteltu luettelo. Kenttien nimiss\u00e4 kirjainkoolla on merkityst\u00e4.",horizontalGap:"Kahden osoitetarran v\u00e4liin j\u00e4\u00e4v\u00e4 tila rivill\u00e4",insetToLabel:"Tila, joka j\u00e4\u00e4 osoitetarran reunan ja tekstin v\u00e4liin",labelFormatDescription:"Miten osoitetarran tyyli esitet\u00e4\u00e4n pienoisohjelman muotoiluasetusten luettelossa",
labelFormatDescriptionHint:"Lis\u00e4kuvauksen ty\u00f6kaluvihje muotoiluasetusten luettelossa",labelHeight:"Kunkin osoitetarran korkeus sivulla",labelWidth:"Kunkin osoitetarran leveys sivulla",localSearchRadius:"M\u00e4\u00e4ritt\u00e4\u00e4 nykyisen kartan keskikohdan ymp\u00e4rill\u00e4 olevan alueen s\u00e4teen. S\u00e4teen avulla arvioidaan geokoodausehdokkaiden sijoitusta, jotta sijaintia l\u00e4hinn\u00e4 olevat ehdokkaat palautetaan ensin",rasterResolution:"100 pikseli\u00e4 tuumaa kohti vastaa suurin piirtein n\u00e4yt\u00f6n tarkkuutta. Mit\u00e4 korkeampi tarkkuus, sit\u00e4 enemm\u00e4n tarvitaan selaimen muistia. Selainten kyky k\u00e4sitell\u00e4 tehokkaasti paljon muistia tarvitsevia toimia vaihtelee.",
selectionListOfOptionsToDisplay:"Valitut kohteet n\u00e4ytet\u00e4\u00e4n asetuksina pienoisohjelmassa; muuta j\u00e4rjestyst\u00e4 halutessasi",verticalGap:"Kahden osoitetarran v\u00e4liin j\u00e4\u00e4v\u00e4 tila palstassa"},propertyLabels:{bufferDefaultDistance:"Puskurin oletuset\u00e4isyys",bufferUnits:"Pienoisohjelmassa m\u00e4\u00e4ritett\u00e4v\u00e4t puskuriyksik\u00f6t",countryRegionCodes:"Maa- tai aluekoodit",description:"Kuvaus",descriptionHint:"Kuvausvihje",displayField:"N\u00e4ytt\u00f6kentt\u00e4",
drawingToolsFreehandPolygon:"alueen piirto vapaalla k\u00e4dell\u00e4",drawingToolsLine:"viiva",drawingToolsPoint:"piste",drawingToolsPolygon:"alue",drawingToolsPolyline:"taiteviiva",enableLocalSearch:"Ota k\u00e4ytt\u00f6\u00f6n paikallinen haku",exactMatch:"Tarkka vastine",fontSizeAlignmentNote:"Tulostusmarginaaleja koskevan huomauksen fonttikoko",gridDarkness:"Ruudukon tummuus",gridlineLeftInset:"Vasemman ruudukkoviivan upotus",gridlineMajorTickMarksGap:"P\u00e4\u00e4jakoviivat joka",gridlineMinorTickMarksGap:"Apujakoviivat joka",
gridlineRightInset:"Oikean ruudukkoviivan upote",labelBorderDarkness:"Osoitetarran reunan tummuus",labelBottomEdge:"Sivun osoitetarrojen alareuna",labelFontSize:"Fontin koko",labelHeight:"Osoitetarran korkeus",labelHorizontalGap:"Vaakasuuntainen v\u00e4li",labelInitialInset:"Osoitetarran tekstin upote",labelLeftEdge:"Sivun osoitetarrojen vasen reuna",labelMaxLineCount:"Rivien enimm\u00e4ism\u00e4\u00e4r\u00e4 osoitetarrassa",labelPageHeight:"Sivun korkeus",labelPageWidth:"Sivun leveys",labelRightEdge:"Sivun osoitetarrojen oikea reuna",
labelsInAColumn:"Osoitetarrojen m\u00e4\u00e4r\u00e4 palstassa",labelsInARow:"Osoitetarrojen m\u00e4\u00e4r\u00e4 rivill\u00e4",labelTopEdge:"Sivun osoitetarrojen yl\u00e4reuna",labelVerticalGap:"Pystysuuntainen v\u00e4li",labelWidth:"Osoitetarran leveys",limitSearchToMapExtent:"Etsi vain nykyisest\u00e4 karttalaajuudesta",maximumResults:"Tulosten enimm\u00e4ism\u00e4\u00e4r\u00e4",maximumSuggestions:"Ehdotusten enimm\u00e4ism\u00e4\u00e4r\u00e4",minimumScale:"V\u00e4himm\u00e4ismittakaava",name:"Nimi",
percentBlack:"% musta",pixels:"pikseli\u00e4",pixelsPerInch:"pikseleit\u00e4 tuumaa kohti",placeholderText:"Muuttujan teksti",placeholderTextForAllSources:"Paikkamerkkiteksti haulle kaikista l\u00e4hteist\u00e4",radius:"S\u00e4de",rasterResolution:"Rasteriresoluutio",searchFields:"Hakukent\u00e4t",showAlignmentAids:"N\u00e4yt\u00e4 kohdistuksen apuviivat sivulla",showGridTickMarks:"N\u00e4yt\u00e4 ruudukon apuviivat",showLabelOutlines:"N\u00e4yt\u00e4 osoitetarrojen \u00e4\u00e4riviivat",showPopupForFoundItem:"N\u00e4yt\u00e4 l\u00f6ydetyn kohteen tai sijainnin ponnahdusikkuna",
tool:"Ty\u00f6kalut",units:"Yksik\u00f6t",url:"URL-osoite",urlToGeometryService:"Geometriapalvelun URL-osoite",useRelatedRecords:"K\u00e4yt\u00e4 siihen liittyvi\u00e4 tietueita",useSecondarySearchLayer:"K\u00e4yt\u00e4 toissijaista valintatasoa",useSelectionDrawTools:"K\u00e4yt\u00e4 valinnan piirtoty\u00f6kaluja",useVectorFonts:"K\u00e4yt\u00e4 vektorifontteja (vain latinalaisen merkist\u00f6n fontit)",zoomScale:"Tarkennustaso"},buttons:{addAddressSource:"Lis\u00e4\u00e4 karttataso, joka sis\u00e4lt\u00e4\u00e4 osoitetarrat ponnahdusikkunassa",
addLabelFormat:"Lis\u00e4\u00e4 osoitetarran muotoilu",addSearchSource:"Lis\u00e4\u00e4 haun l\u00e4hde",set:"Aseta"},placeholders:{averyExample:"esim. Avery(r)-osoitetarra ${averyPartNumber}",countryRegionCodes:"esim. USA,CHN",descriptionCSV:"Pilkuin erotetut arvot",descriptionPDF:"PDF-osoitetarra ${heightLabelIn} x ${widthLabelIn} tuumaa; ${labelsPerPage} sivua kohti"},tooltips:{getWebmapFeatureLayer:"Hae kohdekarttataso web-kartasta",openCountryCodes:"Hanki lis\u00e4tietoja koodeista napsauttamalla",
openFieldSelector:"Avaa kentt\u00e4valitsin napsauttamalla",setAndValidateURL:"M\u00e4\u00e4rit\u00e4 ja validoi URL-osoite"},problems:{noAddresseeLayers:"M\u00e4\u00e4rit\u00e4 v\u00e4hint\u00e4\u00e4n yksi vastaanottajan karttataso",noBufferUnitsForDrawingTools:"M\u00e4\u00e4rit\u00e4 v\u00e4hint\u00e4\u00e4n yksi puskuriyksikk\u00f6 piirtoty\u00f6kaluja varten",noBufferUnitsForSearchSource:"M\u00e4\u00e4rit\u00e4 v\u00e4hint\u00e4\u00e4n yksi puskuriyksikk\u00f6 haun l\u00e4hdett\u00e4 ${sourceName} varten",
noGeometryServiceURL:"M\u00e4\u00e4rit\u00e4 geometriapalvelun URL-osoite",noNotificationLabelFormats:"M\u00e4\u00e4rit\u00e4 v\u00e4hint\u00e4\u00e4n yksi ilmoituksen tunnustekstimuoto",noSearchSourceFields:"M\u00e4\u00e4rit\u00e4 v\u00e4hint\u00e4\u00e4n yksi hakukentt\u00e4 haun l\u00e4hdett\u00e4 ${sourceName} varten",noSearchSourceURL:"M\u00e4\u00e4rit\u00e4 URL-osoite haun l\u00e4hdett\u00e4 ${sourceName} varten"},_localized:{}}});